<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:creativeCommons="http://backend.userland.com/creativeCommonsRssModule" xmlns:re="http://purl.org/atompub/rank/1.0">
    <title type="text">Newest questions tagged fastapi - Stack Overflow</title>
    <link rel="self" href="https://stackoverflow.com/feeds/tag?tagnames=fastapi&amp;sort=newest" type="application/atom+xml" />
    <link rel="alternate" href="https://stackoverflow.com/questions/tagged/?tagnames=fastapi&amp;sort=newest" type="text/html" />
    <subtitle>most recent 30 from stackoverflow.com</subtitle>
    <updated>2021-12-10T19:55:19Z</updated>
    <id>https://stackoverflow.com/feeds/tag?tagnames=fastapi&amp;sort=newest</id>
    <creativeCommons:license>https://creativecommons.org/licenses/by-sa/4.0/rdf</creativeCommons:license>
    <entry>
        <id>https://stackoverflow.com/q/70303715</id>
        <re:rank scheme="https://stackoverflow.com">0</re:rank>
        <title type="text">FastAPI - badly formed hexadecimal UUID string</title>
        <category scheme="https://stackoverflow.com/tags" term="python" />
        <category scheme="https://stackoverflow.com/tags" term="sqlalchemy" />
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <category scheme="https://stackoverflow.com/tags" term="sqlmodel" />
        <author>
            <name>political scientist</name>
            <uri>https://stackoverflow.com/users/10140310</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70303715/fastapi-badly-formed-hexadecimal-uuid-string" />
        <published>2021-12-10T11:17:15Z</published>
        <updated>2021-12-10T15:07:18Z</updated>
        <summary type="html">
            &lt;p&gt;I&#x27;m using FastAPI &amp;amp; SQLModel to insert data into SQLite database (I&#x27;m posting a few fields, then SQLModel adds UUID and datetime fields and inserts into db).&lt;/p&gt;&#xA;&lt;p&gt;While posting data to FastAPI, I occasionally get ValueError:&lt;/p&gt;&#xA;&lt;pre class=&quot;lang-py prettyprint-override&quot;&gt;&lt;code&gt;ValueError: badly formed hexadecimal UUID string&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;I don&#x27;t think there&#x27;s a problem with the data I&#x27;m sending as I&#x27;m not sending &lt;em&gt;id&lt;/em&gt; field, so maybe I misconfigured my SQLModel?&lt;/p&gt;&#xA;&lt;hr /&gt;&#xA;&lt;p&gt;&lt;em&gt;Models&lt;/em&gt;:&lt;/p&gt;&#xA;&lt;pre class=&quot;lang-py prettyprint-override&quot;&gt;&lt;code&gt;# -*- coding: utf-8 -*-&#xA;import uuid&#xA;from typing import Optional&#xA;from datetime import datetime, date&#xA;&#xA;from pydantic import UUID4, HttpUrl&#xA;from sqlmodel import Field, SQLModel&#xA;&#xA;&#xA;class EventBase(SQLModel):&#xA;    title: str&#xA;    text: str&#xA;    date: date&#xA;    URL: HttpUrl&#xA;    category: Optional[str] = Field(default=None) &#xA;&#xA;&#xA;class Event(EventBase, table=True):&#xA;    id: UUID4 = Field(default_factory=uuid.uuid4, primary_key=True)&#xA;    created_at: datetime = Field(default_factory=datetime.utcnow)&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;Edit: decided to try this &lt;a href=&quot;https://github.com/tiangolo/sqlmodel/issues/140#issuecomment-950569807&quot; rel=&quot;nofollow noreferrer&quot;&gt;approach&lt;/a&gt; replacing UUID4 with uuid.UUID, but it didn&#x27;t work as well:&lt;/p&gt;&#xA;&lt;hr /&gt;&#xA;&lt;p&gt;&lt;em&gt;Uvicorn debug&lt;/em&gt;:&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;INFO:     127.0.0.1:53312 - &amp;quot;POST /speeches/ HTTP/1.1&amp;quot; 500 Internal Server Error&#xA;ERROR:    Exception in ASGI application&#xA;Traceback (most recent call last):&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py&amp;quot;, line 373, in run_asgi&#xA;    result = await app(self.scope, self.receive, self.send)&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\uvicorn\middleware\proxy_headers.py&amp;quot;, line 75, in __call__&#xA;    return await self.app(scope, receive, send)&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\uvicorn\middleware\debug.py&amp;quot;, line 96, in __call__&#xA;    raise exc from None&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\uvicorn\middleware\debug.py&amp;quot;, line 93, in __call__&#xA;    await self.app(scope, receive, inner_send)&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\fastapi\applications.py&amp;quot;, line 208, in __call__&#xA;    await super().__call__(scope, receive, send)&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\starlette\applications.py&amp;quot;, line 112, in __call__&#xA;    await self.middleware_stack(scope, receive, send)&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\starlette\middleware\errors.py&amp;quot;, line 181, in __call__&#xA;    raise exc&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\starlette\middleware\errors.py&amp;quot;, line 159, in __call__&#xA;    await self.app(scope, receive, _send)&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\starlette\exceptions.py&amp;quot;, line 82, in __call__&#xA;    raise exc&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\starlette\exceptions.py&amp;quot;, line 71, in __call__&#xA;    await self.app(scope, receive, sender)&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\starlette\routing.py&amp;quot;, line 656, in __call__&#xA;    await route.handle(scope, receive, send)&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\starlette\routing.py&amp;quot;, line 259, in handle&#xA;    await self.app(scope, receive, send)&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\starlette\routing.py&amp;quot;, line 61, in app&#xA;    response = await func(request)&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\fastapi\routing.py&amp;quot;, line 226, in app&#xA;    raw_response = await run_endpoint_function(&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\fastapi\routing.py&amp;quot;, line 161, in run_endpoint_function&#xA;    return await run_in_threadpool(dependant.call, **values)&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\starlette\concurrency.py&amp;quot;, line 39, in run_in_threadpool&#xA;    return await anyio.to_thread.run_sync(func, *args)&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\anyio\to_thread.py&amp;quot;, line 28, in run_sync&#xA;    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\anyio\_backends\_asyncio.py&amp;quot;, line 818, in run_sync_in_worker_thread&#xA;    return await future&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\anyio\_backends\_asyncio.py&amp;quot;, line 754, in run&#xA;    result = context.run(func, *args)&#xA;  File &amp;quot;.\app\main.py&amp;quot;, line 29, in create_events&#xA;    session.refresh(event)&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\sqlalchemy\orm\session.py&amp;quot;, line 2315, in refresh&#xA;    loading.load_on_ident(&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\sqlalchemy\orm\loading.py&amp;quot;, line 407, in load_on_ident&#xA;    return load_on_pk_identity(&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\sqlalchemy\orm\loading.py&amp;quot;, line 541, in load_on_pk_identity&#xA;    return result.one()&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\sqlalchemy\engine\result.py&amp;quot;, line 1407, in one&#xA;    return self._only_one_row(&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\sqlalchemy\engine\result.py&amp;quot;, line 558, in _only_one_row&#xA;    row = onerow(hard_close=True)&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\sqlalchemy\engine\result.py&amp;quot;, line 1271, in _fetchone_impl&#xA;    return self._real_result._fetchone_impl(hard_close=hard_close)&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\sqlalchemy\engine\result.py&amp;quot;, line 1674, in _fetchone_impl&#xA;    row = next(self.iterator, _NO_ROW)&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\sqlalchemy\orm\loading.py&amp;quot;, line 147, in chunks&#xA;    fetch = cursor._raw_all_rows()&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\sqlalchemy\engine\result.py&amp;quot;, line 392, in _raw_all_rows&#xA;    return [make_row(row) for row in rows]&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\sqlalchemy\engine\result.py&amp;quot;, line 392, in &amp;lt;listcomp&amp;gt;&#xA;    return [make_row(row) for row in rows]&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\sqlalchemy\sql\type_api.py&amp;quot;, line 1537, in process&#xA;    return process_value(value, dialect)&#xA;  File &amp;quot;c:\github\speeches-api\env\lib\site-packages\sqlmodel\sql\sqltypes.py&amp;quot;, line 59, in process_result_value&#xA;    value = uuid.UUID(value)&#xA;  File &amp;quot;C:\Users\user\AppData\Local\Programs\Python\Python38\lib\uuid.py&amp;quot;, line 169, in __init__&#xA;    raise ValueError(&#x27;badly formed hexadecimal UUID string&#x27;)&#xA;ValueError: badly formed hexadecimal UUID string&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;
        </summary>
    </entry>
    <entry>
        <id>https://stackoverflow.com/q/70302056</id>
        <re:rank scheme="https://stackoverflow.com">1</re:rank>
        <title type="text">Define a Pydantic (nested) model</title>
        <category scheme="https://stackoverflow.com/tags" term="python" />
        <category scheme="https://stackoverflow.com/tags" term="json" />
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <category scheme="https://stackoverflow.com/tags" term="pydantic" />
        <author>
            <name>LJG</name>
            <uri>https://stackoverflow.com/users/13983136</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70302056/define-a-pydantic-nested-model" />
        <published>2021-12-10T09:06:11Z</published>
        <updated>2021-12-10T15:17:26Z</updated>
        <summary type="html">
            &lt;p&gt;If I use GET (given an id) I get a JSON like:&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;{&#xA;    &amp;quot;data&amp;quot;: {&#xA;        &amp;quot;id&amp;quot;: &amp;quot;81&amp;quot;,&#xA;        &amp;quot;ks&amp;quot;: {&#xA;            &amp;quot;k1&amp;quot;: 25,&#xA;            &amp;quot;k2&amp;quot;: 5&#xA;        },&#xA;        &amp;quot;items&amp;quot;: [&#xA;            {&#xA;                &amp;quot;id&amp;quot;: 1,&#xA;                &amp;quot;name&amp;quot;: &amp;quot;John&amp;quot;,&#xA;                &amp;quot;surname&amp;quot;: &amp;quot;Smith&amp;quot;&#xA;            },&#xA;            {&#xA;                &amp;quot;id&amp;quot;: 2,&#xA;                &amp;quot;name&amp;quot;: &amp;quot;Jane&amp;quot;,&#xA;                &amp;quot;surname&amp;quot;: &amp;quot;Doe&amp;quot;&#xA;            }&#xA;        ]&#xA;    },&#xA;    &amp;quot;server-time&amp;quot;: &amp;quot;2021-12-09 14:18:40&amp;quot;&#xA;}&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;with the particular case (if id does not exist):&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;{&#xA;    &amp;quot;data&amp;quot;: {&#xA;        &amp;quot;id&amp;quot;: -1,&#xA;        &amp;quot;ks&amp;quot;: &amp;quot;&amp;quot;,&#xA;        &amp;quot;items&amp;quot;: []&#xA;    },&#xA;    &amp;quot;server-time&amp;quot;: &amp;quot;2021-12-10 09:35:22&amp;quot;&#xA;}&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;I would like to create a Pydantic model for managing this data structure (I mean to formally define these objects).&#xA;What is the smartest way to manage this data structure by creating classes (possibly nested)?&lt;/p&gt;&#xA;
        </summary>
    </entry>
    <entry>
        <id>https://stackoverflow.com/q/70300675</id>
        <re:rank scheme="https://stackoverflow.com">0</re:rank>
        <title type="text">FastAPI, uvicorn.run() always create 3 instances, but I want it 1 instance</title>
        <category scheme="https://stackoverflow.com/tags" term="python" />
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <category scheme="https://stackoverflow.com/tags" term="uvicorn" />
        <author>
            <name>John</name>
            <uri>https://stackoverflow.com/users/7790894</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70300675/fastapi-uvicorn-run-always-create-3-instances-but-i-want-it-1-instance" />
        <published>2021-12-10T06:43:30Z</published>
        <updated>2021-12-10T06:49:59Z</updated>
        <summary type="html">
            &lt;p&gt;I run FastAPI at PyCharm IDE and it always run 3 workers.&#xA;I don&#x27;t know why, but, the last instance created is being accessed on every API call.&lt;/p&gt;&#xA;&lt;p&gt;Could anyone can help how can I get single running worker?&lt;/p&gt;&#xA;&lt;p&gt;Code:&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;import uvicorn&#xA;from fastapi import FastAPI&#xA;from fastapi.templating import Jinja2Templates&#xA;from starlette.middleware.cors import CORSMiddleware&#xA;&#xA;app = FastAPI()&#xA;app.add_middleware(CORSMiddleware,&#xA;                   allow_origins=[&amp;quot;*&amp;quot;],&#xA;                   allow_methods=[&amp;quot;*&amp;quot;],&#xA;                   allow_headers=[&amp;quot;*&amp;quot;])&#xA;print(f&amp;quot;main.py with :{app}&amp;quot;)&#xA;&#xA;&#xA;@app.get(&#x27;/&#x27;)&#xA;def home():&#xA;    return &amp;quot;Hello&amp;quot;&#xA;&#xA;&#xA;if __name__ == &amp;quot;__main__&amp;quot;:&#xA;    uvicorn.run(&amp;quot;main:app&amp;quot;, host=&amp;quot;0.0.0.0&amp;quot;, port=8000, reload=False, log_level=&amp;quot;debug&amp;quot;, debug=True,&#xA;                workers=1, limit_concurrency=1, limit_max_requests=1)&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;Console output:&lt;/p&gt;&#xA;&lt;blockquote&gt;&#xA;&lt;pre&gt;&lt;code&gt;/Users/user/.pyenv/versions/3.7.10/bin/python /Users/user/github/my-project/backend/main.py&#xA;main.py with :&amp;lt;fastapi.applications.FastAPI object at 0x102b35d50&amp;gt;&#xA;INFO:     Will watch for changes in these directories: [&#x27;/Users/user/github/my-project/backend&#x27;]&#xA;INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL&#x2B;C to quit)&#xA;INFO:     Started reloader process [96259] using statreload&#xA;main.py with :&amp;lt;fastapi.applications.FastAPI object at 0x10daadf50&amp;gt;&#xA;main.py with :&amp;lt;fastapi.applications.FastAPI object at 0x1106bfe50&amp;gt;&#xA;INFO:     Started server process [96261]&#xA;INFO:     Waiting for application startup.&#xA;INFO:     Application startup complete.&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;/blockquote&gt;&#xA;
        </summary>
    </entry>
    <entry>
        <id>https://stackoverflow.com/q/70298294</id>
        <re:rank scheme="https://stackoverflow.com">0</re:rank>
        <title type="text">Docker-compose cant find .sh file</title>
        <category scheme="https://stackoverflow.com/tags" term="docker" />
        <category scheme="https://stackoverflow.com/tags" term="docker-compose" />
        <category scheme="https://stackoverflow.com/tags" term="sh" />
        <category scheme="https://stackoverflow.com/tags" term="gunicorn" />
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <author>
            <name>Muhammad Fhadli</name>
            <uri>https://stackoverflow.com/users/16755045</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70298294/docker-compose-cant-find-sh-file" />
        <published>2021-12-10T00:11:26Z</published>
        <updated>2021-12-10T07:02:45Z</updated>
        <summary type="html">
            &lt;p&gt;I am going to run a shell script inside a docker-compose entrypoint. But when i do &lt;code&gt;docker-compose up&lt;/code&gt;, the gunicorn is starting but it &lt;strong&gt;cant&lt;/strong&gt; found the shell script. Everything works fine without the shell script. But I just want to add the shell script because i need to set some parameters.&lt;/p&gt;&#xA;&lt;p&gt;This is my &lt;code&gt;docker-compose.yml&lt;/code&gt;&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;version: &amp;quot;3.7&amp;quot;&#xA;services:&#xA;  my-container:&#xA;    image: my_image:latest&#xA;    volumes:&#xA;      - ${LOGDIR}:/app/log/&#xA;      - ${SCRIPTS}:/app/scripts/&#xA;    ports:&#xA;      - ${PORT}:80&#xA;    entrypoint: &#xA;      - /bin/sh&#xA;      - /app/scripts/api_reload.sh&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;This is inside &lt;code&gt;api_reload.sh&lt;/code&gt;&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;# !/usr/bin/env&#xA;&#xA;gunicorn app.inf.api.api_pks:app \&#xA;    -b 0.0.0.0:80 \&#xA;    -k uvicorn.workers.UvicornWorker \&#xA;    --timeout 1000&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;This is the error info&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;Recreating information-extraction1 ... done&#xA;Attaching to information-extraction_my-container_1&#xA;: not found_1  | /app/scripts/api_reload.sh: 3: /app/scripts/api_reload.sh:&#xA;my-container_1  | [2021-12-10 00:01:20 &#x2B;0000] [8] [INFO] Starting gunicorn 20.0.4&#xA;my-container_1  | [2021-12-10 00:01:20 &#x2B;0000] [8] [INFO] Listening at: http://127.0.0.1:8000 (8)&#xA;my-container_1  | [2021-12-10 00:01:20 &#x2B;0000] [8] [INFO] Using worker: sync&#xA;my-container_1  | [2021-12-10 00:01:20 &#x2B;0000] [10] [INFO] Booting worker with pid: 10&#xA;my-container_1  | 2021-12-10 00:01:21,130 - INFO - api - &amp;lt;module&amp;gt;, line 50: PREDICTION HAS BEEN STARTED&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;Thank you for your help&lt;/p&gt;&#xA;
        </summary>
    </entry>
    <entry>
        <id>https://stackoverflow.com/q/70298161</id>
        <re:rank scheme="https://stackoverflow.com">0</re:rank>
        <title type="text">Docker: ERROR: relation &quot;users&quot; does not exist at character 13</title>
        <category scheme="https://stackoverflow.com/tags" term="python" />
        <category scheme="https://stackoverflow.com/tags" term="postgresql" />
        <category scheme="https://stackoverflow.com/tags" term="docker" />
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <author>
            <name>Sumit Dadwal</name>
            <uri>https://stackoverflow.com/users/16945470</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70298161/docker-error-relation-users-does-not-exist-at-character-13" />
        <published>2021-12-09T23:49:52Z</published>
        <updated>2021-12-09T23:49:52Z</updated>
        <summary type="html">
            &lt;p&gt;I am trying to dockerize my app made with Python and FastAPI. I successfully created the images and container.&lt;/p&gt;&#xA;&lt;p&gt;I tried to dockerize my postgres database it was done successfully until I try to create a new user. It throws the following error:&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt; ERROR:  relation &amp;quot;users&amp;quot; does not exist at character 13&#xA;10 02:24:37.586 UTC [71] STATEMENT:  INSERT INTO users (email, password) VALUES (&#x27;sumitdadwal11@gmail.com&#x27;, &#x27;$2b$12$VNya4IkKSGCuapswkJrh3u6POJVsdU2GSeIaV/ya4GprxNqEt5oim&#x27;) RETURNING users.id&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;It shows the following error in my FastAPI app image:&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt; Traceback (most recent call last):&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py&amp;quot;, line 1802, in _execute_context&#xA;&#xA;    self.dialect.do_execute(&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py&amp;quot;, line 719, in do_execute&#xA;&#xA;    cursor.execute(statement, parameters)&#xA;&#xA;psycopg2.errors.UndefinedTable: relation &amp;quot;users&amp;quot; does not exist&#xA;&#xA;LINE 1: INSERT INTO users (email, password) VALUES (&#x27;sumitdadwal11@g...&#xA;&#xA;                    ^&#xA;&#xA;    The above exception was the direct cause of the following exception:&#xA;&#xA;&#xA;Traceback (most recent call last):&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py&amp;quot;, line 376, in run_asgi&#xA;&#xA;    result = await app(self.scope, self.receive, self.send)&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py&amp;quot;, line 75, in __call__&#xA;&#xA;    return await self.app(scope, receive, send)&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/fastapi/applications.py&amp;quot;, line 208, in __call__&#xA;&#xA;    await super().__call__(scope, receive, send)&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/starlette/applications.py&amp;quot;, line 112, in __call__&#xA;&#xA;    await self.middleware_stack(scope, receive, send)&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py&amp;quot;, line 181, in __call__&#xA;&#xA;    raise exc&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py&amp;quot;, line 159, in __call__&#xA;&#xA;    await self.app(scope, receive, _send)&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py&amp;quot;, line 84, in __call__&#xA;&#xA;    await self.app(scope, receive, send)&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/starlette/exceptions.py&amp;quot;, line 82, in __call__&#xA;&#xA;    raise exc&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/starlette/exceptions.py&amp;quot;, line 71, in __call__&#xA;&#xA;    await self.app(scope, receive, sender)&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/starlette/routing.py&amp;quot;, line 656, in __call__&#xA;&#xA;    await route.handle(scope, receive, send)&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/starlette/routing.py&amp;quot;, line 259, in handle&#xA;&#xA;    await self.app(scope, receive, send)&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/starlette/routing.py&amp;quot;, line 61, in app&#xA;&#xA;    response = await func(request)&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/fastapi/routing.py&amp;quot;, line 226, in app&#xA;&#xA;    raw_response = await run_endpoint_function(&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/fastapi/routing.py&amp;quot;, line 161, in run_endpoint_function&#xA;&#xA;    return await run_in_threadpool(dependant.call, **values)&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/starlette/concurrency.py&amp;quot;, line 39, in run_in_threadpool&#xA;&#xA;    return await anyio.to_thread.run_sync(func, *args)&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/anyio/to_thread.py&amp;quot;, line 28, in run_sync&#xA;&#xA;    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py&amp;quot;, line 818, in run_sync_in_worker_thread&#xA;&#xA;    return await future&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py&amp;quot;, line 754, in run&#xA;&#xA;    result = context.run(func, *args)&#xA;&#xA;  File &amp;quot;/usr/src/app/./app/routers/user.py&amp;quot;, line 18, in create_user&#xA;&#xA;    db.commit()&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py&amp;quot;, line 1428, in commit&#xA;&#xA;    self._transaction.commit(_to_root=self.future)&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py&amp;quot;, line 829, in commit&#xA;&#xA;    self._prepare_impl()&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py&amp;quot;, line 808, in _prepare_impl&#xA;&#xA;    self.session.flush()&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py&amp;quot;, line 3345, in flush&#xA;&#xA;    self._flush(objects)&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py&amp;quot;, line 3485, in _flush&#xA;&#xA;    transaction.rollback(_capture_exception=True)&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py&amp;quot;, line 70, in __exit__&#xA;&#xA;    compat.raise_(&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py&amp;quot;, line 207, in raise_&#xA;&#xA;    raise exception&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py&amp;quot;, line 3445, in _flush&#xA;&#xA;    flush_context.execute()&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py&amp;quot;, line 456, in execute&#xA;&#xA;    rec.execute(self)&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py&amp;quot;, line 630, in execute&#xA;&#xA;    util.preloaded.orm_persistence.save_obj(&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py&amp;quot;, line 244, in save_obj&#xA;&#xA;    _emit_insert_statements(&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py&amp;quot;, line 1221, in _emit_insert_statements&#xA;&#xA;    result = connection._execute_20(&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py&amp;quot;, line 1614, in _execute_20&#xA;&#xA;    return meth(self, args_10style, kwargs_10style, execution_options)&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py&amp;quot;, line 325, in _execute_on_connection&#xA;&#xA;    return connection._execute_clauseelement(&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py&amp;quot;, line 1481, in _execute_clauseelement&#xA;&#xA;    ret = self._execute_context(&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py&amp;quot;, line 1845, in _execute_context&#xA;&#xA;    self._handle_dbapi_exception(&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py&amp;quot;, line 2026, in _handle_dbapi_exception&#xA;&#xA;    util.raise_(&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py&amp;quot;, line 207, in raise_&#xA;&#xA;    raise exception&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py&amp;quot;, line 1802, in _execute_context&#xA;&#xA;    self.dialect.do_execute(&#xA;&#xA;  File &amp;quot;/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py&amp;quot;, line 719, in do_execute&#xA;&#xA;    cursor.execute(statement, parameters)&#xA;&#xA;sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation &amp;quot;users&amp;quot; does not exist&#xA;&#xA;LINE 1: INSERT INTO users (email, password) VALUES (&#x27;sumitdadwal11@g...&#xA;&#xA;                    ^&#xA;&#xA;&#xA;[SQL: INSERT INTO users (email, password) VALUES (%(email)s, %(password)s) RETURNING users.id]&#xA;&#xA;[parameters: {&#x27;email&#x27;: &#x27;sumitdadwal11@gmail.com&#x27;, &#x27;password&#x27;: &#x27;$2b$12$5tcxP4b0hwVJpmHfyF10wuosYsdIxBkm1nhk1b1BZlLFZyCymodhK&#x27;}]&#xA;&#xA;(Background on this error at: https://sqlalche.me/e/14/f405)&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;This is my docker-compose.yml file:&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;   version: &amp;quot;3&amp;quot;&#xA;services: &#xA;  api:&#xA;    build: .&#xA;    ports:&#xA;      - 8000:8000&#xA;    # env_file:&#xA;    #      ./.env&#xA;    environment:&#xA;      - DATABASE_HOSTNAME=postgres&#xA;      - DATABASE_PORT=5432&#xA;      - DATABASE_PASSWORD=password123&#xA;      - DATABASE_NAME=fastapi&#xA;      - DATABASE_USERNAME=postgres&#xA;      - SECRET_KEY=secretkeysecretkeysecretkeysecretkey&#xA;      - ALGORITHM=HS256&#xA;      - ACCESS_TOKEN_EXPIRE_MINUTES=30&#xA;  postgres:&#xA;    image: postgres&#xA;    environment:&#xA;      - POSTGRES_PASSWORD=password123&#xA;      - POSTGRES_DB=fastapi&#xA;    &#xA;    volumes:&#xA;      - postgres-db:/var/lib/postgresql/data&#xA;&#xA;volumes:&#xA;  postgres-db:&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;This is my Dockerfile:&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;  FROM python:3.9.9&#xA;&#xA;WORKDIR /usr/src/app&#xA;&#xA;COPY requirements.txt ./&#xA;&#xA;RUN pip install --no-cache-dir -r requirements.txt&#xA;&#xA;COPY . .&#xA;&#xA;CMD [&amp;quot;uvicorn&amp;quot;, &amp;quot;app.main:app&amp;quot;, &amp;quot;--host&amp;quot;, &amp;quot;0.0.0.0&amp;quot;, &amp;quot;--port&amp;quot;, &amp;quot;8000&amp;quot;]&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;First I thought somethings wrong with my code but it is working fine when I am running it locally on my system.&lt;/p&gt;&#xA;&lt;p&gt;Also, I am very new to docker.&lt;/p&gt;&#xA;&lt;p&gt;I have tried different online solution but nothing worked out.&lt;/p&gt;&#xA;&lt;p&gt;Please let me know if you need any additional information.&lt;/p&gt;&#xA;&lt;p&gt;Thanks in advance!&lt;/p&gt;&#xA;
        </summary>
    </entry>
    <entry>
        <id>https://stackoverflow.com/q/70294037</id>
        <re:rank scheme="https://stackoverflow.com">1</re:rank>
        <title type="text">FastAPI Jinja2Templates - Error whie providing external directory structure?</title>
        <category scheme="https://stackoverflow.com/tags" term="python" />
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <author>
            <name>diaryfolio</name>
            <uri>https://stackoverflow.com/users/1221358</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70294037/fastapi-jinja2templates-error-whie-providing-external-directory-structure" />
        <published>2021-12-09T17:16:55Z</published>
        <updated>2021-12-10T13:18:08Z</updated>
        <summary type="html">
            &lt;p&gt;This is specifically to FastAPI &amp;amp; Jinja2Templates (&lt;a href=&quot;https://fastapi.tiangolo.com/advanced/templates/&quot; rel=&quot;nofollow noreferrer&quot;&gt;https://fastapi.tiangolo.com/advanced/templates/&lt;/a&gt;) . If the directory of the templates &amp;amp; static files are within the python script directory it all works. But if the directory structure is outside the script, then it is NOT picking up&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;from fastapi import FastAPI, Request&#xA;from fastapi.staticfiles import StaticFiles&#xA;from fastapi.templating import Jinja2Templates&#xA;&#xA;app = FastAPI()&#xA;p06_dir=&amp;quot;../artefacts/p06&amp;quot;&#xA;templates_dir=p06_dir &#x2B; &#x27;/templates&#x27;&#xA;static_dir=p06_dir &#x2B; &#x27;/static&#x27;&#xA;# Prints the directory correctly and files accessible&#xA;print(static_dir)&#xA;&#xA;# Below fails&#xA;# RuntimeError: Directory &#x27;static&#x27; does not exist&#xA;app.mount(static_dir, StaticFiles(directory=&amp;quot;static&amp;quot;), name=&amp;quot;static&amp;quot;)&#xA;# Below also fails&#xA;templates = Jinja2Templates(directory=templates_dir)&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;pre&gt;&lt;code&gt;&#xA;.&#xA;&#x251C;&#x2500;&#x2500; artefacts&#xA;&#x2502;&#xA0;&#xA0; &#x2514;&#x2500;&#x2500; p06&#xA;&#x2502;&#xA0;&#xA0;     &#x2514;&#x2500;&#x2500; static&#xA;&#x2502;&#xA0;&#xA0;         &#x251C;&#x2500;&#x2500; p06.css&#xA;&#x2502;&#xA0;&#xA0;         &#x2514;&#x2500;&#x2500; vue.js&#xA;&#x2514;&#x2500;&#x2500; software&#xA;    &#x2514;&#x2500;&#x2500; api.py&#xA;&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;if I use normal python3 sys module and OS module, all works but when it comes to FastApi, it is not finding the directory structure. Does anyone know a sample of FAstAPI/Jinja2Templates which uses templates externally?&lt;/p&gt;&#xA;
        </summary>
    </entry>
    <entry>
        <id>https://stackoverflow.com/q/70291602</id>
        <re:rank scheme="https://stackoverflow.com">0</re:rank>
        <title type="text">OpenAPI generation workaround for tuple list in FastAPI</title>
        <category scheme="https://stackoverflow.com/tags" term="python" />
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <category scheme="https://stackoverflow.com/tags" term="python-typing" />
        <category scheme="https://stackoverflow.com/tags" term="pydantic" />
        <author>
            <name>Sty</name>
            <uri>https://stackoverflow.com/users/1545888</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70291602/openapi-generation-workaround-for-tuple-list-in-fastapi" />
        <published>2021-12-09T14:25:30Z</published>
        <updated>2021-12-09T14:38:00Z</updated>
        <summary type="html">
            &lt;p&gt;For an API I am developing with FastAPI at the moment, I&#x27;m running into issues with nested tuples:&lt;/p&gt;&#xA;&lt;pre class=&quot;lang-py prettyprint-override&quot;&gt;&lt;code&gt;from typing import Annotated&#xA;from pydantic import BaseModel, NonNegativeInt, Field&#xA;&#xA;class SomeData(BaseModel):&#xA;  my_tuple_list_field: Annotated[&#xA;    list[Tuple[NonNegativeInt, NonNegativeInt]],&#xA;    Field(description=&amp;quot;Some descriptive text to put into the API docs&amp;quot;)&#xA;  ]&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;Note: I&#x27;m using &lt;code&gt;mypy&lt;/code&gt; for type checking, due to which &lt;code&gt;pydantic&lt;/code&gt;&#x27;s &lt;code&gt;conlist&lt;/code&gt; etc. are not an option to use here, hence the &lt;code&gt;Annotated&lt;/code&gt; usage.&lt;/p&gt;&#xA;&lt;p&gt;While the API works fine in this manner and tests to ensure that all list entries only have two enties succeed, the generated OpenAPI specs are faulty (the list items here are specified as type &amp;quot;minimum&amp;quot; which is not declared anywhere):&lt;/p&gt;&#xA;&lt;pre class=&quot;lang-json prettyprint-override&quot;&gt;&lt;code&gt;&amp;quot;SomeData&amp;quot;: {&#xA;  &amp;quot;title&amp;quot;: &amp;quot;SomeData&amp;quot;,&#xA;  &amp;quot;required&amp;quot;: [&#xA;    &amp;quot;my_tuple_list_field&amp;quot;&#xA;  ],&#xA;  &amp;quot;type&amp;quot;: &amp;quot;object&amp;quot;,&#xA;  &amp;quot;properties&amp;quot;: {&#xA;    &amp;quot;my_tuple_list_field&amp;quot;: {&#xA;      &amp;quot;title&amp;quot;: &amp;quot;My Tuple List Field&amp;quot;,&#xA;      &amp;quot;type&amp;quot;: &amp;quot;array&amp;quot;,&#xA;      &amp;quot;items&amp;quot;: {&#xA;        &amp;quot;type&amp;quot;: &amp;quot;array&amp;quot;,&#xA;        &amp;quot;items&amp;quot;: {&#xA;          &amp;quot;type&amp;quot;: &amp;quot;minimum&amp;quot;&#xA;        }&#xA;      },&#xA;      &amp;quot;description&amp;quot;: &amp;quot;Some descriptive text to put into the API docs&amp;quot;&#xA;    }&#xA;  }&#xA;}&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;I&#x27;ve tried a few workarounds so far:&lt;/p&gt;&#xA;&lt;ul&gt;&#xA;&lt;li&gt;replacing the &lt;code&gt;Tuple&lt;/code&gt; with an &lt;code&gt;Annotated[list[NonNegativeInt], Field(min_items=2, max_items=2)]&lt;/code&gt;, which results in a usable OpenAPI spec, but the items restrictions on the inner &lt;code&gt;Annotated&lt;/code&gt; get completely ignored, also in the context of unit tests&lt;/li&gt;&#xA;&lt;li&gt;Declaring a separate &lt;code&gt;NamedTuple&lt;/code&gt; subclass and using that in the &lt;code&gt;Annotated[list[...]]&lt;/code&gt;, but while the pure &lt;code&gt;Tuple[...]&lt;/code&gt; notation at least generates an OpenAPI spec (even though faulty), &lt;a href=&quot;https://github.com/tiangolo/fastapi/issues/3782&quot; rel=&quot;nofollow noreferrer&quot;&gt;this option results in actual errors on spec generation&lt;/a&gt;&lt;/li&gt;&#xA;&lt;/ul&gt;&#xA;&lt;p&gt;Accordingly, I&#x27;m now wondering how to get a reasonable generated OpenAPI spec while keeping my test assumptions intact. Given that according issues have been raised with FastAPI&#x27;s developer for quite some time already, it appears unrealistic that a proper fix in the library would be available soon. What else can be done in the meantime to remedy the situation? Is there perhaps a way to locally modify the resulting OpenAPI spec directly? Or could some other form of Iterable be derived from that offers relatively straightforward length check implementation while at the same time being handled well enough by &lt;code&gt;pydantic&lt;/code&gt; and &lt;code&gt;fastapi&lt;/code&gt; to generate the desired OpenAPI item (I assume one could always write a full-fledged &lt;code&gt;list&lt;/code&gt; subclass, but judging by the effort that would have to go into this, I&#x27;d prefer higher-level options)?&lt;/p&gt;&#xA;
        </summary>
    </entry>
    <entry>
        <id>https://stackoverflow.com/q/70287744</id>
        <re:rank scheme="https://stackoverflow.com">2</re:rank>
        <title type="text">Set specific pydantic object field to not be serialised when null</title>
        <category scheme="https://stackoverflow.com/tags" term="python" />
        <category scheme="https://stackoverflow.com/tags" term="json" />
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <category scheme="https://stackoverflow.com/tags" term="pydantic" />
        <author>
            <name>timj11dude</name>
            <uri>https://stackoverflow.com/users/4580610</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70287744/set-specific-pydantic-object-field-to-not-be-serialised-when-null" />
        <published>2021-12-09T09:47:39Z</published>
        <updated>2021-12-10T13:57:26Z</updated>
        <summary type="html">
            &lt;p&gt;I have a pydantic object definition that includes an optional field. I am looking to be able to configure the field to only be serialised if it is not &lt;code&gt;None&lt;/code&gt;.&lt;/p&gt;&#xA;&lt;pre class=&quot;lang-py prettyprint-override&quot;&gt;&lt;code&gt;class MyObject(BaseModel):&#xA;   id: str&#xA;   msg: Optional[str] = None&#xA;   pri: Optional[int] = None&#xA;&#xA;MyObject(id=&amp;quot;123&amp;quot;).json()  # ideal output: {&amp;quot;id&amp;quot;: &amp;quot;123&amp;quot;, &amp;quot;pri&amp;quot;: null}&#xA;MyObject(id=&amp;quot;123&amp;quot;, msg=&amp;quot;hello&amp;quot;).json()  # ideal output: {&amp;quot;id&amp;quot;: &amp;quot;123&amp;quot;, &amp;quot;msg&amp;quot;: &amp;quot;hello&amp;quot;, &amp;quot;pri&amp;quot;: null}&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;I would like to be able to specify the field precisely, as this object will be nested, and there are other optional fields that should be returned, regardless of whether they are &lt;code&gt;None&lt;/code&gt; or not.&#xA;The &lt;a href=&quot;https://pydantic-docs.helpmanual.io/usage/exporting_models/#modeljson&quot; rel=&quot;nofollow noreferrer&quot;&gt;solution to set json option&lt;/a&gt; &lt;code&gt;exclude_none&lt;/code&gt; to &lt;code&gt;True&lt;/code&gt; won&#x27;t work for this purpose.&lt;/p&gt;&#xA;
        </summary>
    </entry>
    <entry>
        <id>https://stackoverflow.com/q/70286745</id>
        <re:rank scheme="https://stackoverflow.com">0</re:rank>
        <title type="text">In FastAPI Getting &#x27;Not authenticated&#x27; Error after authenticate</title>
        <category scheme="https://stackoverflow.com/tags" term="python" />
        <category scheme="https://stackoverflow.com/tags" term="oauth-2.0" />
        <category scheme="https://stackoverflow.com/tags" term="jwt" />
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <category scheme="https://stackoverflow.com/tags" term="bearer-token" />
        <author>
            <name>hope_karthi</name>
            <uri>https://stackoverflow.com/users/17632847</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70286745/in-fastapi-getting-not-authenticated-error-after-authenticate" />
        <published>2021-12-09T08:32:01Z</published>
        <updated>2021-12-09T08:32:01Z</updated>
        <summary type="html">
            &lt;h1&gt;File dir&lt;/h1&gt;&#xA;&lt;blockquote&gt;&#xA;&lt;p&gt;fastapi_jwt&lt;/p&gt;&#xA;&lt;blockquote&gt;&#xA;&lt;p&gt;.env&#xA;main.py&#xA;app&lt;/p&gt;&#xA;&lt;blockquote&gt;&#xA;&lt;p&gt;api.py&#xA;model.py&#xA;auth&lt;/p&gt;&#xA;&lt;blockquote&gt;&#xA;&lt;p&gt;auth_bearer.py&#xA;auth_handler.py&lt;/p&gt;&#xA;&lt;/blockquote&gt;&#xA;&lt;/blockquote&gt;&#xA;&lt;/blockquote&gt;&#xA;&lt;/blockquote&gt;&#xA;&lt;hr /&gt;&#xA;&lt;h3&gt;fastapi_jwt/.env&lt;/h3&gt;&#xA;&lt;pre&gt;&lt;code&gt;secret=please_please_update_me_please&#xA;algorithm=HS256&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;hr /&gt;&#xA;&lt;h3&gt;fastapi_jwt/main.py&lt;/h3&gt;&#xA;&lt;pre&gt;&lt;code&gt;import uvicorn&#xA;&#xA;if __name__ == &amp;quot;__main__&amp;quot;:&#xA;    uvicorn.run(&amp;quot;app.api:app&amp;quot;, host=&amp;quot;127.0.0.1&amp;quot;, port=8000, reload=True)&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;hr /&gt;&#xA;&lt;h3&gt;fastapi_jwt/app/api.py&lt;/h3&gt;&#xA;&lt;pre&gt;&lt;code&gt;from fastapi import FastAPI, Body, Depends&#xA;from starlette.responses import HTMLResponse&#xA;&#xA;from app.model import PostSchema, UserSchema, UserLoginSchema&#xA;from app.auth.auth_bearer import JWTBearer&#xA;from app.auth.auth_handler import signJWT&#xA;&#xA;app = FastAPI()&#xA;&#xA;@app.get(&amp;quot;/&amp;quot;, tags=[&amp;quot;root&amp;quot;])&#xA;async def read_root():&#xA;    return {&amp;quot;message&amp;quot;: &amp;quot;Welcome to your blog!.&amp;quot;}&#xA;&#xA;from app.model import PostSchema&#xA;&#xA;posts = [&#xA;    {&#xA;        &amp;quot;id&amp;quot;: 1,&#xA;        &amp;quot;title&amp;quot;: &amp;quot;Pancake&amp;quot;,&#xA;        &amp;quot;content&amp;quot;: &amp;quot;Lorem Ipsum ...&amp;quot;&#xA;    }&#xA;]&#xA;&#xA;users = []&#xA;&#xA;@app.get(&amp;quot;/posts&amp;quot;, tags=[&amp;quot;posts&amp;quot;])&#xA;async def get_posts() -&amp;gt; dict:&#xA;    return { &amp;quot;data&amp;quot;: posts }&#xA;&#xA;&#xA;@app.get(&amp;quot;/posts/{id}&amp;quot;, tags=[&amp;quot;posts&amp;quot;])&#xA;async def get_single_post(id: int) -&amp;gt; dict:&#xA;    if id &amp;gt; len(posts):&#xA;        return {&#xA;            &amp;quot;error&amp;quot;: &amp;quot;No such post with the supplied ID.&amp;quot;&#xA;        }&#xA;&#xA;    for post in posts:&#xA;        if post[&amp;quot;id&amp;quot;] == id:&#xA;            return {&#xA;                &amp;quot;data&amp;quot;: post&#xA;            }&#xA;@app.get(&amp;quot;/post&amp;quot;, dependencies=[Depends(JWTBearer())], tags=[&amp;quot;posts&amp;quot;])&#xA;@app.post(&amp;quot;/post&amp;quot;, dependencies=[Depends(JWTBearer())], tags=[&amp;quot;posts&amp;quot;])&#xA;async def add_post(post: PostSchema) -&amp;gt; dict:&#xA;    post.id = len(posts) &#x2B; 1&#xA;    posts.append(post.dict())&#xA;    return {&amp;quot;result&amp;quot;:&amp;quot;Post added successfully&amp;quot;}&#xA;&#xA;@app.post(&amp;quot;/user/signup&amp;quot;, tags=[&amp;quot;user&amp;quot;])&#xA;async def create_user(user: UserSchema = Body(...)):&#xA;    users.append(user) # replace with db call, making sure to hash the password first&#xA;    return signJWT(user.email)&#xA;&#xA;def check_user(data: UserLoginSchema):&#xA;    for user in users:&#xA;        if user.email == data.email and user.password == data.password:&#xA;            return True&#xA;    return False&#xA;&#xA;@app.post(&amp;quot;/user/login&amp;quot;, tags=[&amp;quot;user&amp;quot;])&#xA;async def user_login(user: UserLoginSchema = Body(...)):&#xA;    if check_user(user):&#xA;        return signJWT(user.email)&#xA;    return {&#xA;        &amp;quot;error&amp;quot;: &amp;quot;Wrong login details!&amp;quot;&#xA;    }&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;hr /&gt;&#xA;&lt;h3&gt;fastapi_jwt/app/model.py&lt;/h3&gt;&#xA;&lt;pre&gt;&lt;code&gt;from pydantic import BaseModel, Field, EmailStr&#xA;    &#xA;    &#xA;    class PostSchema(BaseModel):&#xA;        id: int = Field(default=None)&#xA;        title: str = Field(...)&#xA;        content: str = Field(...)&#xA;    &#xA;        class Config:&#xA;            schema_extra = {&#xA;                &amp;quot;example&amp;quot;: {&#xA;                    &amp;quot;title&amp;quot;: &amp;quot;Securing FastAPI applications with JWT.&amp;quot;,&#xA;                    &amp;quot;content&amp;quot;: &amp;quot;In this tutorial, you&#x27;ll learn how to secure your application by enabling authentication using JWT. We&#x27;ll be using PyJWT to sign, encode and decode JWT tokens....&amp;quot;&#xA;                }&#xA;            }    &#xA;    class UserSchema(BaseModel):&#xA;        fullname: str = Field(...)&#xA;        email: EmailStr = Field(...)&#xA;        password: str = Field(...)&#xA;    &#xA;        class Config:&#xA;            schema_extra = {&#xA;                &amp;quot;example&amp;quot;: {&#xA;                    &amp;quot;fullname&amp;quot;: &amp;quot;Abdulazeez Abdulazeez Adeshina&amp;quot;,&#xA;                    &amp;quot;email&amp;quot;: &amp;quot;abdulazeez@x.com&amp;quot;,&#xA;                    &amp;quot;password&amp;quot;: &amp;quot;weakpassword&amp;quot;&#xA;                }&#xA;            }&#xA;    &#xA;    class UserLoginSchema(BaseModel):&#xA;        email: EmailStr = Field(...)&#xA;        password: str = Field(...)&#xA;    &#xA;        class Config:&#xA;            schema_extra = {&#xA;                &amp;quot;example&amp;quot;: {&#xA;                    &amp;quot;email&amp;quot;: &amp;quot;abdulazeez@x.com&amp;quot;,&#xA;                    &amp;quot;password&amp;quot;: &amp;quot;weakpassword&amp;quot;&#xA;                }&#xA;            }&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;hr /&gt;&#xA;&lt;h3&gt;fastapi_jwt/app/auth/auth_bearer.py&lt;/h3&gt;&#xA;&lt;pre&gt;&lt;code&gt;from fastapi import Request, HTTPException&#xA;from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials&#xA;&#xA;from .auth_handler import decodeJWT&#xA;&#xA;&#xA;class JWTBearer(HTTPBearer):&#xA;    def __init__(self, auto_error: bool = True):&#xA;        super(JWTBearer, self).__init__(auto_error=auto_error)&#xA;&#xA;    async def __call__(self, request: Request):&#xA;        credentials: HTTPAuthorizationCredentials = await super(JWTBearer, self).__call__(request)&#xA;        if credentials:&#xA;            if not credentials.scheme == &amp;quot;Bearer&amp;quot;:&#xA;                raise HTTPException(status_code=403, detail=&amp;quot;Invalid authentication scheme.&amp;quot;)&#xA;            if not self.verify_jwt(credentials.credentials):&#xA;                raise HTTPException(status_code=403, detail=&amp;quot;Invalid token or expired token.&amp;quot;)&#xA;            return credentials.credentials&#xA;        else:&#xA;            raise HTTPException(status_code=403, detail=&amp;quot;Invalid authorization code.&amp;quot;)&#xA;&#xA;    def verify_jwt(self, jwtoken: str) -&amp;gt; bool:&#xA;        isTokenValid: bool = False&#xA;&#xA;        try:&#xA;            payload = decodeJWT(jwtoken)&#xA;        except:&#xA;            payload = None&#xA;        if payload:&#xA;            isTokenValid = True&#xA;        return isTokenValid&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;hr /&gt;&#xA;&lt;h3&gt;fastapi_jwt/app/auth/auth_handler.py&lt;/h3&gt;&#xA;&lt;pre&gt;&lt;code&gt;import time&#xA;from typing import Dict&#xA;&#xA;import jwt&#xA;from decouple import config&#xA;&#xA;&#xA;JWT_SECRET = config(&amp;quot;secret&amp;quot;)&#xA;JWT_ALGORITHM = config(&amp;quot;algorithm&amp;quot;)&#xA;&#xA;&#xA;def token_response(token: str):&#xA;    return {&#xA;        &amp;quot;access_token&amp;quot;: token&#xA;    }&#xA;&#xA;def signJWT(user_id: str) -&amp;gt; Dict[str, str]:&#xA;    payload = {&#xA;        &amp;quot;user_id&amp;quot;: user_id,&#xA;        &amp;quot;expires&amp;quot;: time.time() &#x2B; 600&#xA;    }&#xA;    token = jwt.encode(payload, JWT_SECRET, algorithm=JWT_ALGORITHM)&#xA;&#xA;    return token_response(token)&#xA;&#xA;def decodeJWT(token: str) -&amp;gt; dict:&#xA;    try:&#xA;        decoded_token = jwt.decode(token, JWT_SECRET, algorithms=[JWT_ALGORITHM])&#xA;        return decoded_token if decoded_token[&amp;quot;expires&amp;quot;] &amp;gt;= time.time() else None&#xA;    except:&#xA;        return {}&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;I run &#x27;main.py&#x27;, the url&#xA;&amp;quot; &lt;a href=&quot;http://127.0.0.1:8000/post&quot; rel=&quot;nofollow noreferrer&quot;&gt;http://127.0.0.1:8000/post&lt;/a&gt; &amp;quot; shows the output &amp;quot;{&amp;quot;detail&amp;quot;:&amp;quot;Not authenticated&amp;quot;}&amp;quot;.&#xA;So go to the url &amp;quot; &lt;a href=&quot;http://127.0.0.1:8000/docs&quot; rel=&quot;nofollow noreferrer&quot;&gt;http://127.0.0.1:8000/docs&lt;/a&gt; &amp;quot; for FastAPI -Swagger UI interface like&#xA;&lt;a href=&quot;https://i.stack.imgur.com/WMqs6.png&quot; rel=&quot;nofollow noreferrer&quot;&gt;this&lt;/a&gt;.&#xA;Then I signup and login to get the jwt token and use that token to &lt;a href=&quot;https://i.stack.imgur.com/qo21M.png&quot; rel=&quot;nofollow noreferrer&quot;&gt;authenticate&lt;/a&gt;, then go to url&#xA;&amp;quot; /post &amp;quot; in FastAPI -Swagger UI and execute to get the output &lt;a href=&quot;https://i.stack.imgur.com/7ftJU.png&quot; rel=&quot;nofollow noreferrer&quot;&gt;{&amp;quot;result&amp;quot;: &amp;quot;Post added successfully&amp;quot;}&lt;/a&gt;.&#xA;But in &amp;quot; &lt;a href=&quot;http://127.0.0.1:8000/post&quot; rel=&quot;nofollow noreferrer&quot;&gt;http://127.0.0.1:8000/post&lt;/a&gt; &amp;quot; got an error and show the same ouput &amp;quot;{&amp;quot;detail&amp;quot;:&amp;quot;Not authenticated&amp;quot;}&amp;quot;&lt;/p&gt;&#xA;
        </summary>
    </entry>
    <entry>
        <id>https://stackoverflow.com/q/70285830</id>
        <re:rank scheme="https://stackoverflow.com">-4</re:rank>
        <title type="text">Command Error: &quot;Command errored out with exit status 1&quot; while installing fastAPI [closed]</title>
        <category scheme="https://stackoverflow.com/tags" term="python" />
        <category scheme="https://stackoverflow.com/tags" term="api" />
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <author>
            <name>AD5639</name>
            <uri>https://stackoverflow.com/users/17633039</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70285830/command-error-command-errored-out-with-exit-status-1-while-installing-fastapi" />
        <published>2021-12-09T07:01:10Z</published>
        <updated>2021-12-09T07:06:13Z</updated>
        <summary type="html">
            &lt;p&gt;I&#x27;m following along this tutorial &lt;a href=&quot;https://www.freecodecamp.org/news/creating-apis-with-python-free-19-hour-course/&quot; rel=&quot;nofollow noreferrer&quot;&gt;https://www.freecodecamp.org/news/creating-apis-with-python-free-19-hour-course/&lt;/a&gt; and am trying to install fastAPI but I keep getting this &lt;a href=&quot;https://i.stack.imgur.com/GhWLy.jpg&quot; rel=&quot;nofollow noreferrer&quot;&gt;error&lt;/a&gt;&lt;/p&gt;&#xA;
        </summary>
    </entry>
    <entry>
        <id>https://stackoverflow.com/q/70285342</id>
        <re:rank scheme="https://stackoverflow.com">0</re:rank>
        <title type="text">Fastapi FileResponse multiple files</title>
        <category scheme="https://stackoverflow.com/tags" term="file" />
        <category scheme="https://stackoverflow.com/tags" term="download" />
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <author>
            <name>luoshuxiao</name>
            <uri>https://stackoverflow.com/users/11408942</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70285342/fastapi-fileresponse-multiple-files" />
        <published>2021-12-09T05:59:59Z</published>
        <updated>2021-12-10T07:54:10Z</updated>
        <summary type="html">
            &lt;p&gt;How can I use Fastapi FileResponse as a download interface for multiple files instead of a single file, Here is my code:&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;    def get_file(file_path):&#xA;        path = BASE_DIR &#x2B; os.sep &#x2B; file_path&#xA;        if not os.path.exists(path):&#xA;            return MyResponse(code=ResponseCodeEnum.not_exist)&#xA;        try:&#xA;            return [FileResponse(path &#x2B; os.sep &#x2B; file_name) for file_name in os.listdir(path)]&#xA;        except Exception as exc:&#xA;            return MyResponse(code=ResponseCodeEnum.unknown)&#xA;&#xA;    @_app.get(&#x27;/file_download/&#x27;, description=&#x27;tttttt&#x27;)&#xA;    async def file_download(&#xA;            file_path: str = Query(None, description=&#x27;qqqqqq&#x27;),&#xA;            path_type: FilePathEnum = Query(FilePathEnum.services_file, description=&#x27;sssssssss&#x27;),&#xA;            file_tag: str = Query(None, description=&#x27;eeeeeeeeeee&#x27;),&#xA;            file_name: str = Query(None, description=&#x27;ttttttttttt&#x27;),&#xA;    ):&#xA;        if file_path:&#xA;            if not any((&#xA;                    file_path.startswith(&#x27;services_file&#x27;),&#xA;                    file_path.startswith(&#x27;shared_library&#x27;),&#xA;            )):&#xA;                return MyResponse(code=ResponseCodeEnum.illegal)&#xA;            return get_file(file_path)&#xA;        # file_path = path_type &#x2B; (os.sep &#x2B; file_tag if file_tag else &#x27;&#x27;) &#x2B; (os.sep &#x2B; file_name if file_name else &#x27;&#x27;)&#xA;        file_path = path_type &#x2B; (os.sep &#x2B; file_tag if file_tag else &#x27;&#x27;)&#xA;        return get_file(file_path)&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;I know it doesn&#x27;t work&#xFF1A;&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;            return [FileResponse(path &#x2B; os.sep &#x2B; file_name) for file_name in os.listdir(path)]&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;Should I convert the file to binary or Base64 instead of FileResponse?&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;   async def get_file(file_path):&#xA;       path = BASE_DIR &#x2B; os.sep &#x2B; file_path&#xA;       if not os.path.exists(path):&#xA;           return MyResponse(code=ResponseCodeEnum.not_exist)&#xA;       try:&#xA;           # return [FileResponse(path &#x2B; os.sep &#x2B; file_name) for file_name in os.listdir(path)]&#xA;           files = []&#xA;           for file_name in os.listdir(path):&#xA;               async with aiofiles.open(path &#x2B; os.sep &#x2B; file_name, mode=&#x27;r&#x27;,encoding=&#x27;utf8&#x27;) as f:&#xA;                   contents = await f.read()&#xA;                   files.append({&#x27;file_name&#x27;: file_name, &#x27;file&#x27;: contents})&#xA;           return MyResponse(data=files)&#xA;       except Exception as exc:&#xA;           return MyResponse(code=ResponseCodeEnum.unknown)&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;Please tell me how to do better&lt;/p&gt;&#xA;
        </summary>
    </entry>
    <entry>
        <id>https://stackoverflow.com/q/70283186</id>
        <re:rank scheme="https://stackoverflow.com">-1</re:rank>
        <title type="text">FastAPI wait for a specific api call before answering the current one</title>
        <category scheme="https://stackoverflow.com/tags" term="python" />
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <author>
            <name>Mahmoud Al</name>
            <uri>https://stackoverflow.com/users/9446266</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70283186/fastapi-wait-for-a-specific-api-call-before-answering-the-current-one" />
        <published>2021-12-09T00:00:34Z</published>
        <updated>2021-12-09T00:07:21Z</updated>
        <summary type="html">
            &lt;p&gt;What I need to do is quite simple yet hard to implement. How can we build an API endpoint that when called will wait for another api endpoint to be called using specific id in order to reply. Example:&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;@app.get(&amp;quot;/who_are_you&amp;quot;)&#xA;async def way():&#xA;    ##wait until auth route is called with specific id&#xA;    return {&amp;quot;result&amp;quot;: &amp;quot;my name is:{}&amp;quot;.format(res)}&#xA;&#xA;@app.get(&amp;quot;/auth/&amp;lt;rid&amp;gt;&amp;quot;)&#xA;async def auth(rid):&#xA;    ## perform database request and return result to way function that will resume running.&#xA;    return {&amp;quot;result&amp;quot;: &amp;quot;resume&amp;quot;}&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;Please help&lt;/p&gt;&#xA;
        </summary>
    </entry>
    <entry>
        <id>https://stackoverflow.com/q/70283067</id>
        <re:rank scheme="https://stackoverflow.com">-1</re:rank>
        <title type="text">The field cannot receive the data</title>
        <category scheme="https://stackoverflow.com/tags" term="python" />
        <category scheme="https://stackoverflow.com/tags" term="sqlalchemy" />
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <category scheme="https://stackoverflow.com/tags" term="pydantic" />
        <author>
            <name>Jacaranda</name>
            <uri>https://stackoverflow.com/users/16792099</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70283067/the-field-cannot-receive-the-data" />
        <published>2021-12-08T23:41:57Z</published>
        <updated>2021-12-08T23:41:57Z</updated>
        <summary type="html">
            &lt;p&gt;I am using fastapi with a pydantic model and sqlalchemy to make an api that looks like a social media (creates users,posts,and votes) based on a youtube project of sanjeev (it has recently released in free code camp) and I don&#x27;t know what to do because I copied the code and changed it almost nothing,it cannot receive the data that I put in the request&#xA;The fixture code is:&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt; def test_users(client):&#xA;    users_data = [&#xA;        {&#xA;            &amp;quot;email&amp;quot;: &amp;quot;julio@gmail.com&amp;quot;,&#xA;            &amp;quot;password&amp;quot;: &amp;quot;123&amp;quot;&#xA;        },&#xA;        {&#xA;            &amp;quot;email&amp;quot;: &amp;quot;estelson@gmail.com&amp;quot;,&#xA;            &amp;quot;password&amp;quot;: &amp;quot;123&amp;quot;&#xA;        },&#xA;        {&#xA;            &amp;quot;email&amp;quot;: &amp;quot;joana@gmail.com&amp;quot;,&#xA;            &amp;quot;password&amp;quot;: &amp;quot;123&amp;quot;&#xA;        },&#xA;        {&#xA;            &amp;quot;email&amp;quot;: &amp;quot;julie@gmail.com&amp;quot;,&#xA;            &amp;quot;password&amp;quot;: &amp;quot;123&amp;quot;&#xA;        }&#xA;    ]&#xA;    new_users = list()&#xA;    for user_data in users_data:&#xA;        res = client.post(&amp;quot;/users/&amp;quot;, json=user_data)&#xA;        assert res.status_code == 201&#xA;        new_user = res.json()&#xA;        new_user[&#x27;password&#x27;] = user_data[&#x27;password&#x27;]&#xA;        new_users.append(new_user)&#xA;    return new_users&#xA;&#xA;@pytest.fixture&#xA;def test_posts(test_users, session):&#xA;    posts_data = [&#xA;        {&#xA;            &#x27;title&#x27;: &#x27;first title&#x27;,&#xA;            &amp;quot;content&amp;quot;: &amp;quot;first content&amp;quot;,&#xA;            &amp;quot;owner_id&amp;quot;: test_users[0][&#x27;id&#x27;]&#xA;        }, {&#xA;            &amp;quot;title&amp;quot;: &amp;quot;2nd title&amp;quot;,&#xA;            &amp;quot;content&amp;quot;: &amp;quot;2nd content&amp;quot;,&#xA;            &amp;quot;owner_id&amp;quot;: test_users[0][&#x27;id&#x27;]&#xA;        },&#xA;        {&#xA;            &amp;quot;title&amp;quot;: &amp;quot;3rd title&amp;quot;,&#xA;            &amp;quot;content&amp;quot;: &amp;quot;3rd content&amp;quot;,&#xA;            &amp;quot;owner_id&amp;quot;: test_users[0][&#x27;id&#x27;]&#xA;        }, {&#xA;            &amp;quot;title&amp;quot;: &amp;quot;3rd title&amp;quot;,&#xA;            &amp;quot;content&amp;quot;: &amp;quot;3rd content&amp;quot;,&#xA;            &amp;quot;owner_id&amp;quot;: test_users[1][&#x27;id&#x27;]&#xA;        }, {&#xA;            &amp;quot;title&amp;quot;: &amp;quot;4rd title&amp;quot;,&#xA;            &amp;quot;content&amp;quot;: &amp;quot;4rd content&amp;quot;,&#xA;            &amp;quot;owner_id&amp;quot;: test_users[1][&#x27;id&#x27;]&#xA;        }]&#xA;&#xA;    def create_post_model(post):&#xA;        return models.Post(**post)&#xA;&#xA;    post_map = map(create_post_model, posts_data)&#xA;    posts = list(post_map)&#xA;    session.add_all(posts)&#xA;    session.commit()&#xA;    # for post in posts_data:&#xA;    #     post_model = models.Post(**post)&#xA;    #     session.add(post_model)&#xA;    #     session.commit()&#xA;&#xA;    posts = session.query(models.Post).all()&#xA;    return posts&#xA;&#xA;&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;Then the tests code :&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;def test_get_all_posts(authorized_client, test_posts):&#xA;    res = authorized_client.get(&#x27;/posts/&#x27;)&#xA;&#xA;    def validate(post):&#xA;        return schemas.PostOut(**post)&#xA;    posts_map = map(validate, list(res.json()))&#xA;    posts_list = list(posts_map)&#xA;    print(posts_list)&#xA;&#xA;    assert len(res.json()) == len(test_posts)&#xA;    assert res.status_code == 200&#xA;&#xA;&#xA;def test_get_one_post(authorized_client, test_posts):&#xA;    res = authorized_client.get(f&amp;quot;/posts/{test_posts[0].id}&amp;quot;)&#xA;    post = schemas.PostOut(**res.json())&#xA;    print(post.Post.title, post.Post.content,&#xA;          post.Post.published, post.Post.id)&#xA;    assert post.Post.id == test_posts[0].id&#xA;    assert post.Post.content == test_posts[0].content&#xA;    assert post.Post.title == test_posts[0].title&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;The routes:&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;@router.get(&#x27;/&#x27;, response_model=List[schemas.PostOut])&#xA;def get_posts(db: Session = Depends(get_db), current_user: int = Depends(oauth2.get_current_user), limit: int = 10, skip: int = 0, search: Optional[str] = &amp;quot;&amp;quot;):&#xA;    posts = db.query(models.Post, func.count(models.Likes.post_id).label(&#x27;likes&#x27;), func.count(models.Dislikes.post_id).label(&#x27;dislikes&#x27;)).join(&#xA;        models.Likes, models.Likes.post_id == models.Post.id, isouter=True).join(&#xA;        models.Dislikes, models.Dislikes.post_id == models.Post.id, isouter=True).group_by(models.Post.id).filter(models.Post.title.contains(search)).limit(limit).offset(skip).all()&#xA;&#xA;    return posts&#xA;&#xA;&#xA;@router.get(&#x27;/{id}&#x27;, response_model=schemas.PostOut)&#xA;def get_post(id: int, db: Session = Depends(get_db), current_user: int = Depends(oauth2.get_current_user)):&#xA;    post = db.query(models.Post, func.count(models.Likes.post_id).label(&#x27;likes&#x27;), func.count(models.Dislikes.post_id).label(&#x27;dislikes&#x27;)).join(&#xA;        models.Likes, models.Likes.post_id == models.Post.id, isouter=True).join(models.Dislikes, models.Dislikes.post_id == models.Post.id, isouter=True).group_by(models.Post.id).filter(models.Post.id == id).first()&#xA;    if not post:&#xA;        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND,&#xA;                            detail=f&#x27;post with id : {id} was not found&#x27;)&#xA;&#xA;    return post&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;The schemas :&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;class PostBase(BaseModel):&#xA;    title: str&#xA;    content: str&#xA;    published: bool = True&#xA;&#xA;class Post(PostBase):&#xA;    id: int&#xA;    created_at: datetime&#xA;    owner_id: int&#xA;    owner: UserOut&#xA;&#xA;    class Config:&#xA;        orm_mode = True&#xA;&#xA;&#xA;class PostOut(PostBase):&#xA;    Post: Post&#xA;&#xA;    class Config:&#xA;        orm_mode = True&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;And finally the errors&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;authorized_client = &amp;lt;starlette.testclient.TestClient object at 0x00000260702DB5E0&amp;gt;&#xA;test_posts = [&amp;lt;app.models.Post object at 0x000002607028C190&amp;gt;, &amp;lt;app.models.Post object at 0x000002607028C340&amp;gt;, &amp;lt;app.models.Post object at &#xA;0x00000260702DB790&amp;gt;, &amp;lt;app.models.Post object at 0x000002606FB9BE80&amp;gt;, &amp;lt;app.models.Post object at 0x000002607027E1C0&amp;gt;]&#xA;&#xA;    def test_get_all_posts(authorized_client, test_posts):&#xA;&amp;gt;       res = authorized_client.get(&#x27;/posts/&#x27;)&#xA;&#xA;tests\test_post.py:38:&#xA;_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  &#xA;venv\lib\site-packages\requests\sessions.py:555: in get&#xA;    return self.request(&#x27;GET&#x27;, url, **kwargs)&#xA;venv\lib\site-packages\starlette\testclient.py:468: in request&#xA;    return super().request(&#xA;venv\lib\site-packages\requests\sessions.py:542: in request&#xA;    resp = self.send(prep, **send_kwargs)&#xA;venv\lib\site-packages\requests\sessions.py:655: in send&#xA;    r = adapter.send(request, **kwargs)&#xA;venv\lib\site-packages\starlette\testclient.py:266: in send&#xA;    raise exc&#xA;venv\lib\site-packages\starlette\testclient.py:263: in send&#xA;    portal.call(self.app, scope, receive, send)&#xA;venv\lib\site-packages\anyio\from_thread.py:240: in call&#xA;    return cast(T_Retval, self.start_task_soon(func, *args).result())&#xA;C:\Python39\lib\concurrent\futures\_base.py:445: in result&#xA;    return self.__get_result()&#xA;C:\Python39\lib\concurrent\futures\_base.py:390: in __get_result&#xA;    raise self._exception&#xA;venv\lib\site-packages\anyio\from_thread.py:187: in _call_func&#xA;    retval = await retval&#xA;venv\lib\site-packages\fastapi\applications.py:208: in __call__&#xA;    await super().__call__(scope, receive, send)&#xA;venv\lib\site-packages\starlette\applications.py:112: in __call__&#xA;    await self.middleware_stack(scope, receive, send)&#xA;venv\lib\site-packages\starlette\middleware\errors.py:181: in __call__&#xA;    raise exc&#xA;venv\lib\site-packages\starlette\middleware\errors.py:159: in __call__&#xA;    await self.app(scope, receive, _send)&#xA;venv\lib\site-packages\starlette\middleware\cors.py:84: in __call__&#xA;    await self.app(scope, receive, send)&#xA;venv\lib\site-packages\starlette\exceptions.py:82: in __call__&#xA;    raise exc&#xA;venv\lib\site-packages\starlette\exceptions.py:71: in __call__&#xA;    await self.app(scope, receive, sender)&#xA;venv\lib\site-packages\starlette\routing.py:656: in __call__&#xA;    await route.handle(scope, receive, send)&#xA;venv\lib\site-packages\starlette\routing.py:259: in handle&#xA;    await self.app(scope, receive, send)&#xA;venv\lib\site-packages\starlette\routing.py:61: in app&#xA;    response = await func(request)&#xA;venv\lib\site-packages\fastapi\routing.py:234: in app&#xA;    response_data = await serialize_response(&#xA;_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  &#xA;&#xA;    async def serialize_response(&#xA;        *,&#xA;        field: Optional[ModelField] = None,&#xA;        response_content: Any,&#xA;        include: Optional[Union[SetIntStr, DictIntStrAny]] = None,&#xA;        exclude: Optional[Union[SetIntStr, DictIntStrAny]] = None,&#xA;        by_alias: bool = True,&#xA;        exclude_unset: bool = False,&#xA;        exclude_defaults: bool = False,&#xA;        exclude_none: bool = False,&#xA;        is_coroutine: bool = True,&#xA;    ) -&amp;gt; Any:&#xA;        if field:&#xA;            errors = []&#xA;            response_content = _prepare_response_content(&#xA;                response_content,&#xA;                exclude_unset=exclude_unset,&#xA;                exclude_defaults=exclude_defaults,&#xA;                exclude_none=exclude_none,&#xA;            )&#xA;            if is_coroutine:&#xA;                value, errors_ = field.validate(response_content, {}, loc=(&amp;quot;response&amp;quot;,))&#xA;            else:&#xA;                value, errors_ = await run_in_threadpool(&#xA;                    field.validate, response_content, {}, loc=(&amp;quot;response&amp;quot;,)&#xA;                )&#xA;            if isinstance(errors_, ErrorWrapper):&#xA;                errors.append(errors_)&#xA;            elif isinstance(errors_, list):&#xA;                errors.extend(errors_)&#xA;            if errors:&#xA;&amp;gt;               raise ValidationError(errors, field.type_)&#xA;E               pydantic.error_wrappers.ValidationError: 10 validation errors for PostOut&#xA;E               response -&amp;gt; 0 -&amp;gt; title&#xA;E                 field required (type=value_error.missing)&#xA;E               response -&amp;gt; 0 -&amp;gt; content&#xA;E                 field required (type=value_error.missing)&#xA;E               response -&amp;gt; 1 -&amp;gt; title&#xA;E                 field required (type=value_error.missing)&#xA;E               response -&amp;gt; 1 -&amp;gt; content&#xA;E                 field required (type=value_error.missing)&#xA;E               response -&amp;gt; 2 -&amp;gt; title&#xA;E                 field required (type=value_error.missing)&#xA;E               response -&amp;gt; 2 -&amp;gt; content&#xA;E                 field required (type=value_error.missing)&#xA;E               response -&amp;gt; 3 -&amp;gt; title&#xA;E                 field required (type=value_error.missing)&#xA;E               response -&amp;gt; 3 -&amp;gt; content&#xA;E                 field required (type=value_error.missing)&#xA;E               response -&amp;gt; 4 -&amp;gt; title&#xA;E                 field required (type=value_error.missing)&#xA;E               response -&amp;gt; 4 -&amp;gt; content&#xA;E                 field required (type=value_error.missing)&#xA;&#xA;venv\lib\site-packages\fastapi\routing.py:137: ValidationError&#xA;__________________________________________________________ test_get_one_post ___________________________________________________________ &#xA;&#xA;authorized_client = &amp;lt;starlette.testclient.TestClient object at 0x0000026070302430&amp;gt;&#xA;test_posts = [&amp;lt;app.models.Post object at 0x000002607091D730&amp;gt;, &amp;lt;app.models.Post object at 0x000002607091D520&amp;gt;, &amp;lt;app.models.Post object at &#xA;0x000002607091DB80&amp;gt;, &amp;lt;app.models.Post object at 0x000002607091D9D0&amp;gt;, &amp;lt;app.models.Post object at 0x000002607091D460&amp;gt;]&#xA;&#xA;    def test_get_one_post(authorized_client, test_posts):&#xA;&amp;gt;       res = authorized_client.get(f&amp;quot;/posts/{test_posts[0].id}&amp;quot;)&#xA;&#xA;tests\test_post.py:51: &#xA;_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  &#xA;venv\lib\site-packages\requests\sessions.py:555: in get&#xA;    return self.request(&#x27;GET&#x27;, url, **kwargs)&#xA;venv\lib\site-packages\starlette\testclient.py:468: in request&#xA;    return super().request(&#xA;venv\lib\site-packages\requests\sessions.py:542: in request&#xA;    resp = self.send(prep, **send_kwargs)&#xA;venv\lib\site-packages\requests\sessions.py:655: in send&#xA;    r = adapter.send(request, **kwargs)&#xA;venv\lib\site-packages\starlette\testclient.py:266: in send&#xA;    raise exc&#xA;venv\lib\site-packages\starlette\testclient.py:263: in send&#xA;    portal.call(self.app, scope, receive, send)&#xA;venv\lib\site-packages\anyio\from_thread.py:240: in call&#xA;    return cast(T_Retval, self.start_task_soon(func, *args).result())&#xA;C:\Python39\lib\concurrent\futures\_base.py:445: in result&#xA;    return self.__get_result()&#xA;C:\Python39\lib\concurrent\futures\_base.py:390: in __get_result&#xA;    raise self._exception&#xA;venv\lib\site-packages\anyio\from_thread.py:187: in _call_func&#xA;    retval = await retval&#xA;venv\lib\site-packages\fastapi\applications.py:208: in __call__&#xA;    await super().__call__(scope, receive, send)&#xA;venv\lib\site-packages\starlette\applications.py:112: in __call__&#xA;    await self.middleware_stack(scope, receive, send)&#xA;venv\lib\site-packages\starlette\middleware\errors.py:181: in __call__&#xA;    raise exc&#xA;venv\lib\site-packages\starlette\middleware\errors.py:159: in __call__&#xA;    await self.app(scope, receive, _send)&#xA;venv\lib\site-packages\starlette\middleware\cors.py:84: in __call__&#xA;    await self.app(scope, receive, send)&#xA;venv\lib\site-packages\starlette\exceptions.py:82: in __call__&#xA;    raise exc&#xA;venv\lib\site-packages\starlette\exceptions.py:71: in __call__&#xA;    await self.app(scope, receive, sender)&#xA;venv\lib\site-packages\starlette\routing.py:656: in __call__&#xA;    await route.handle(scope, receive, send)&#xA;venv\lib\site-packages\starlette\routing.py:259: in handle&#xA;    await self.app(scope, receive, send)&#xA;venv\lib\site-packages\starlette\routing.py:61: in app&#xA;    response = await func(request)&#xA;venv\lib\site-packages\fastapi\routing.py:234: in app&#xA;    response_data = await serialize_response(&#xA;_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  &#xA;&#xA;    async def serialize_response(&#xA;        *,&#xA;        field: Optional[ModelField] = None,&#xA;        response_content: Any,&#xA;        include: Optional[Union[SetIntStr, DictIntStrAny]] = None,&#xA;        exclude: Optional[Union[SetIntStr, DictIntStrAny]] = None,&#xA;        by_alias: bool = True,&#xA;        exclude_unset: bool = False,&#xA;        exclude_defaults: bool = False,&#xA;        exclude_none: bool = False,&#xA;        is_coroutine: bool = True,&#xA;    ) -&amp;gt; Any:&#xA;        if field:&#xA;            errors = []&#xA;            response_content = _prepare_response_content(&#xA;                response_content,&#xA;                exclude_unset=exclude_unset,&#xA;                exclude_defaults=exclude_defaults,&#xA;                exclude_none=exclude_none,&#xA;            )&#xA;            if is_coroutine:&#xA;                value, errors_ = field.validate(response_content, {}, loc=(&amp;quot;response&amp;quot;,))&#xA;            else:&#xA;                value, errors_ = await run_in_threadpool(&#xA;                    field.validate, response_content, {}, loc=(&amp;quot;response&amp;quot;,)&#xA;                )&#xA;            if isinstance(errors_, ErrorWrapper):&#xA;                errors.append(errors_)&#xA;            elif isinstance(errors_, list):&#xA;                errors.extend(errors_)&#xA;            if errors:&#xA;&amp;gt;               raise ValidationError(errors, field.type_)&#xA;E               pydantic.error_wrappers.ValidationError: 2 validation errors for PostOut&#xA;E               response -&amp;gt; title&#xA;E                 field required (type=value_error.missing)&#xA;E               response -&amp;gt; content&#xA;E                 field required (type=value_error.missing)&#xA;&#xA;venv\lib\site-packages\fastapi\routing.py:137: ValidationError&#xA;======================================================= short test summary info ======================================================== &#xA;FAILED tests/test_post.py::test_get_all_posts - pydantic.error_wrappers.ValidationError: 10 validation errors for PostOut&#xA;FAILED tests/test_post.py::test_get_one_post - pydantic.error_wrappers.ValidationError: 2 validation errors for PostOut&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;If anyone could at least give an opinion of what should be the problem,I would appreciate a lot,this is the second day that I&#x27;m trying to find the mistake but I can&#x27;t,I even looked at the original code,and it looks that they&#x27;re equal&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;&lt;/code&gt;&lt;/pre&gt;&#xA;
        </summary>
    </entry>
    <entry>
        <id>https://stackoverflow.com/q/70282437</id>
        <re:rank scheme="https://stackoverflow.com">0</re:rank>
        <title type="text">Docker containers crashed: /bin/sh: 1: [uvicorn,: not found</title>
        <category scheme="https://stackoverflow.com/tags" term="python" />
        <category scheme="https://stackoverflow.com/tags" term="docker" />
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <author>
            <name>Sumit Dadwal</name>
            <uri>https://stackoverflow.com/users/16945470</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70282437/docker-containers-crashed-bin-sh-1-uvicorn-not-found" />
        <published>2021-12-08T22:24:07Z</published>
        <updated>2021-12-10T01:17:16Z</updated>
        <summary type="html">
            &lt;p&gt;I am new to Docker and trying to Dockerize my FastAPI application.&#xA;First I created a Dockerfile:&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;FROM python:3.9.9&#xA;&#xA;WORKDIR /usr/src/app&#xA;&#xA;COPY requirements.txt ./&#xA;&#xA;RUN pip install --no-cache-dir -r requirements.txt&#xA;&#xA;COPY . .&#xA;&#xA;CMD [&amp;quot;uvicorn&amp;quot;, &amp;quot;app.main:app&amp;quot;, &amp;quot;--host&amp;quot;, &amp;quot;0.0.0.0&amp;quot;, &amp;quot;--port&amp;quot;, &amp;quot;8000&amp;quot;]&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;Then ran the following command:&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;docker build -t fastapi .&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;The command ran successfully.&lt;/p&gt;&#xA;&lt;p&gt;After that I created the following docker-compose.yml:&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;version: &amp;quot;3&amp;quot;&#xA;services: &#xA;  api:&#xA;    build: .&#xA;    ports:&#xA;      - 8000:8000&#xA;    env_file:&#xA;         ./.env&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;Then ran the following command:&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;docker-compose up -d&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;Ran successfully:&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;    Network fastapi_default  Created                              0.7s &#xA; - Container fastapi_api_1  Started &#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;Then to check if its running properly I ran the following command:&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;docker ps -a&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;And it showed that Container exited few seconds after it was created.&lt;/p&gt;&#xA;&lt;p&gt;Then I ran this command:&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;docker logs fastapi_api_1&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;And it says:&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;/bin/sh: 1: [uvicorn,: not found&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;Not sure what is the reason. Tried some solutions that I found online but nothing worked out. I do have uvicorn in my requirements.txt file.&lt;/p&gt;&#xA;&lt;p&gt;Help will be appriciated. Please let me know if additional information is required.&lt;/p&gt;&#xA;
        </summary>
    </entry>
    <entry>
        <id>https://stackoverflow.com/q/70282149</id>
        <re:rank scheme="https://stackoverflow.com">0</re:rank>
        <title type="text">Spawning (and killing) Uvicorn/FastAPI backend from Electron (or Node.js)</title>
        <category scheme="https://stackoverflow.com/tags" term="python" />
        <category scheme="https://stackoverflow.com/tags" term="node.js" />
        <category scheme="https://stackoverflow.com/tags" term="electron" />
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <category scheme="https://stackoverflow.com/tags" term="uvicorn" />
        <author>
            <name>dsholes</name>
            <uri>https://stackoverflow.com/users/6257909</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70282149/spawning-and-killing-uvicorn-fastapi-backend-from-electron-or-node-js" />
        <published>2021-12-08T21:50:51Z</published>
        <updated>2021-12-08T21:50:51Z</updated>
        <summary type="html">
            &lt;p&gt;I&#x27;m building a Python backend for an Electron app using FastAPI (and Uvicorn). I develop on both macOS and Windows, so I&#x27;m looking for a cross-platform solution to the following question.&lt;/p&gt;&#xA;&lt;p&gt;&lt;strong&gt;How can I spawn and gracefully kill a python Uvicorn server from Node.js (specifically the &lt;code&gt;electron.js&lt;/code&gt; script of my Electron app)?&lt;/strong&gt;&lt;/p&gt;&#xA;&lt;p&gt;The only way I&#x27;ve been able to launch the server is with &lt;code&gt;exec&lt;/code&gt; instead of &lt;code&gt;spawn&lt;/code&gt;. So this works:&lt;/p&gt;&#xA;&lt;pre class=&quot;lang-js prettyprint-override&quot;&gt;&lt;code&gt;const { spawn, exec, execFile } = require(&amp;quot;child_process&amp;quot;);&#xA;&#xA;function launchPython() {&#xA;  pythonProcess = exec(&#xA;    &amp;quot;C:\\Users\\user2\\miniconda3\\envs\\myenv\\python.exe .\\py_src\\main.py&amp;quot;&#xA;  );&#xA;  console.log(&amp;quot;Python process started in dev mode&amp;quot;)&#xA;  return pythonProcess;&#xA;}&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;But this does not:&lt;/p&gt;&#xA;&lt;pre class=&quot;lang-js prettyprint-override&quot;&gt;&lt;code&gt;&#xA;function launchPython() {&#xA;  pythonProcess = spawn(&#xA;    &amp;quot;C:\\Users\\user2\\miniconda3\\envs\\myenv\\python.exe .\\py_src\\main.py&amp;quot;&#xA;  );&#xA;  console.log(&amp;quot;Python process started in dev mode&amp;quot;)&#xA;  return pythonProcess;&#xA;}&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;&lt;code&gt;.\py_src\main.py&lt;/code&gt; looks like this:&lt;/p&gt;&#xA;&lt;pre class=&quot;lang-py prettyprint-override&quot;&gt;&lt;code&gt;import uvicorn&#xA;&#xA;&#xA;if __name__ == &amp;quot;__main__&amp;quot;:&#xA;    uvicorn.run(&#xA;        &amp;quot;app.api:app&amp;quot;, &#xA;        host=&amp;quot;0.0.0.0&amp;quot;, &#xA;        port=8000, &#xA;        reload=True&#xA;        )&#xA;&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;Also, upon exiting the Electron app, the Uvicorn server is not killed. The &amp;quot;exit&amp;quot; code in my main &lt;code&gt;electron.js&lt;/code&gt; file is as follows:&lt;/p&gt;&#xA;&lt;pre class=&quot;lang-js prettyprint-override&quot;&gt;&lt;code&gt;app.on(&amp;quot;window-all-closed&amp;quot;, function () {&#xA;  if (process.platform !== &amp;quot;darwin&amp;quot;) {&#xA;    pythonProcess.kill();&#xA;    app.quit();&#xA;    return&#xA;  }&#xA;});&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;So two main questions:&lt;/p&gt;&#xA;&lt;ol&gt;&#xA;&lt;li&gt;Why doesn&#x27;t &lt;code&gt;spawn&lt;/code&gt; work to run the python Uvicorn server (&lt;code&gt;py_src\main.py&lt;/code&gt;)? &lt;strong&gt;NOTE&lt;/strong&gt;: I&#x27;m using a specific python version from a Miniconda environment. Could that be the cause?&lt;/li&gt;&#xA;&lt;li&gt;How can I shutdown the Uvicorn server programmatically when the Electron app exits (because killing the python process that I opened with &lt;code&gt;exec&lt;/code&gt; doesn&#x27;t seem to work)?&lt;/li&gt;&#xA;&lt;/ol&gt;&#xA;&lt;p&gt;Eventually I&#x27;m going to use Pyinstaller to build an executable for the FastAPI backend, and launch it with &lt;code&gt;child_process.execFile&lt;/code&gt;, which is why I need a programmatic way to shutdown the Uvicorn server (e.g. with a &amp;quot;quit&amp;quot; or &amp;quot;shutdown&amp;quot; call to the API)&lt;/p&gt;&#xA;
        </summary>
    </entry>
    <entry>
        <id>https://stackoverflow.com/q/70277785</id>
        <re:rank scheme="https://stackoverflow.com">1</re:rank>
        <title type="text">Getting FastApi StreamedResponse via JS</title>
        <category scheme="https://stackoverflow.com/tags" term="javascript" />
        <category scheme="https://stackoverflow.com/tags" term="fetch" />
        <category scheme="https://stackoverflow.com/tags" term="streaming" />
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <author>
            <name>Andy MGF</name>
            <uri>https://stackoverflow.com/users/4228240</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70277785/getting-fastapi-streamedresponse-via-js" />
        <published>2021-12-08T15:45:31Z</published>
        <updated>2021-12-09T03:26:56Z</updated>
        <summary type="html">
            &lt;p&gt;I am trying to fetch and console.log my data streamed from FastApi via the StreamedResponse using fetch but I cannot get it working. Chrome says &lt;code&gt;Cannot read properties of null (reading &#x27;getReader&#x27;)&lt;/code&gt; because &lt;code&gt;response.body&lt;/code&gt; is null. What am I doing wrong?&lt;/p&gt;&#xA;&lt;p&gt;Server&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;async def foo():&#xA;    for i in range(5):&#xA;        time.sleep(1)&#xA;        yield b&#x27;foobar&#x27;&#xA;&#xA;@app.get(&#x27;/bar&#x27;)&#xA;async def bar():&#xA;    return StreamingResponse(foo(), media_type=&#x27;text/plain&#x27;)&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;client&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;async function buttonclick() {&#xA;        let url = &#x27;http://localhost:8000/bar&#x27;;&#xA;&#xA;        let options = {&#xA;            mode: &#x27;no-cors&#x27;,&#xA;            method: &#x27;GET&#x27;&#xA;        }&#xA;&#xA;        fetch(url, options)&#xA;            .then(processChunkedResponse)&#xA;            .then(onChunkedResponseComplete)&#xA;            .catch(onChunkedResponseError);&#xA;&#xA;    }&#xA;&#xA;&#xA;    function onChunkedResponseComplete(result) {&#xA;        console.log(&#x27;all done!&#x27;, result)&#xA;    }&#xA;&#xA;    function onChunkedResponseError(err) {&#xA;        console.error(err)&#xA;    }&#xA;&#xA;    function processChunkedResponse(response) {&#xA;        var text = &#x27;&#x27;;&#xA;        var reader = response.body.getReader()&#xA;        var decoder = new TextDecoder();&#xA;&#xA;        return readChunk();&#xA;&#xA;        function readChunk() {&#xA;            return reader.read().then(appendChunks);&#xA;        }&#xA;&#xA;        function appendChunks(result) {&#xA;            var chunk = decoder.decode(result.value || new Uint8Array, {stream: !result.done});&#xA;            console.log(&#x27;got chunk of&#x27;, chunk.length, &#x27;bytes&#x27;)&#xA;            text &#x2B;= chunk;&#xA;            console.log(&#x27;text so far is&#x27;, text.length, &#x27;bytes\n&#x27;);&#xA;            if (result.done) {&#xA;                console.log(&#x27;returning&#x27;)&#xA;                return text;&#xA;            } else {&#xA;                console.log(&#x27;recursing&#x27;)&#xA;                return readChunk();&#xA;            }&#xA;        }&#xA;    }&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;
        </summary>
    </entry>
    <entry>
        <id>https://stackoverflow.com/q/70274482</id>
        <re:rank scheme="https://stackoverflow.com">0</re:rank>
        <title type="text">Socketio implementation with FastApi and React</title>
        <category scheme="https://stackoverflow.com/tags" term="python" />
        <category scheme="https://stackoverflow.com/tags" term="reactjs" />
        <category scheme="https://stackoverflow.com/tags" term="websocket" />
        <category scheme="https://stackoverflow.com/tags" term="socket.io" />
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <author>
            <name>targhs</name>
            <uri>https://stackoverflow.com/users/8799471</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70274482/socketio-implementation-with-fastapi-and-react" />
        <published>2021-12-08T11:47:14Z</published>
        <updated>2021-12-08T11:47:14Z</updated>
        <summary type="html">
            &lt;p&gt;I have the following techstack&lt;/p&gt;&#xA;&lt;ol&gt;&#xA;&lt;li&gt;FastApi - backend&lt;/li&gt;&#xA;&lt;li&gt;React - frontend&lt;/li&gt;&#xA;&lt;/ol&gt;&#xA;&lt;p&gt;and want to implement socketio(not Websockets provided by FastApi). It lacks documentation in both FastApi and Socketio&lt;/p&gt;&#xA;
        </summary>
    </entry>
    <entry>
        <id>https://stackoverflow.com/q/70272414</id>
        <re:rank scheme="https://stackoverflow.com">0</re:rank>
        <title type="text">Lots of &quot;Uncaught signal: 6&quot; errors in Cloud Run</title>
        <category scheme="https://stackoverflow.com/tags" term="python-3.x" />
        <category scheme="https://stackoverflow.com/tags" term="docker" />
        <category scheme="https://stackoverflow.com/tags" term="google-cloud-platform" />
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <category scheme="https://stackoverflow.com/tags" term="google-cloud-run" />
        <author>
            <name>Jeremy Schiemann</name>
            <uri>https://stackoverflow.com/users/13400973</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70272414/lots-of-uncaught-signal-6-errors-in-cloud-run" />
        <published>2021-12-08T09:09:15Z</published>
        <updated>2021-12-08T14:23:24Z</updated>
        <summary type="html">
            &lt;p&gt;I have a Python (3.x) webservice deployed in GCP. Everytime Cloud Run is shutting down instances, most noticeably after a big load spike, I get many logs like these &lt;code&gt;Uncaught signal: 6, pid=6, tid=6, fault_addr=0.&lt;/code&gt; together with &lt;code&gt;[CRITICAL] WORKER TIMEOUT (pid:6)&lt;/code&gt; They are always signal 6.&lt;/p&gt;&#xA;&lt;p&gt;The service is using FastAPI and Gunicorn running in a Docker with this start command&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;CMD gunicorn -w 2 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8080 app.__main__:app&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;The service is deployed using Terraform with 1 gig of ram, 2 cpu&#x27;s and the timeout is set to 2 minutes&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;resource &amp;quot;google_cloud_run_service&amp;quot; &amp;lt;ressource-name&amp;gt; {&#xA;  name     = &amp;lt;name&amp;gt;&#xA;  location = &amp;lt;location&amp;gt;&#xA;&#xA;  template {&#xA;    spec {&#xA;      service_account_name = &amp;lt;sa-email&amp;gt;&#xA;      timeout_seconds = 120&#xA;      containers {&#xA;        image = var.image&#xA;        env {&#xA;          name = &amp;quot;GCP_PROJECT&amp;quot;&#xA;          value = var.project&#xA;        }&#xA;        env {&#xA;          name = &amp;quot;BRANCH_NAME&amp;quot;&#xA;          value = var.branch&#xA;        }&#xA;        resources {&#xA;          limits = {&#xA;            cpu = &amp;quot;2000m&amp;quot;&#xA;            memory = &amp;quot;1Gi&amp;quot;&#xA;          }&#xA;        }&#xA;      }&#xA;    }&#xA;  }&#xA;  autogenerate_revision_name = true&#xA;}&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;I have already tried tweaking the resources and timeout in Cloud Run, using the --timeout and --preload flag for gunicorn as that is what people always seem to recommend when googling the problem but all without success. I also dont exactly know why the workers are timing out.&lt;/p&gt;&#xA;
        </summary>
    </entry>
    <entry>
        <id>https://stackoverflow.com/q/70272371</id>
        <re:rank scheme="https://stackoverflow.com">0</re:rank>
        <title type="text">Can I create a service in fastapi using an imported function from another .py file?</title>
        <category scheme="https://stackoverflow.com/tags" term="python" />
        <category scheme="https://stackoverflow.com/tags" term="function" />
        <category scheme="https://stackoverflow.com/tags" term="service" />
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <author>
            <name>Alex</name>
            <uri>https://stackoverflow.com/users/15131186</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70272371/can-i-create-a-service-in-fastapi-using-an-imported-function-from-another-py-fi" />
        <published>2021-12-08T09:05:17Z</published>
        <updated>2021-12-08T10:18:20Z</updated>
        <summary type="html">
            &lt;p&gt;I have written some functions with python in separate files. My task is to transform these functions into services using fastAPI and the services should return a JSON that says if the operation is executed correctly or not (a code and a message).&lt;/p&gt;&#xA;&lt;p&gt;For example, I have a file &lt;code&gt;sum.py&lt;/code&gt; and inside there&#x27;s a function that sums two numbers and returns the result:&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;def sum_of_two_numbers(a,b):&#xA;    tot = a&#x2B;b&#xA;    return tot&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;Let&#x27;s say I want to create a service using fastAPI, do you know if I can import &lt;code&gt;sum_of_two_numbers&lt;/code&gt; from &lt;code&gt;sum&lt;/code&gt; and use &lt;a href=&quot;https://fastapi.tiangolo.com/tutorial/testing/&quot; rel=&quot;nofollow noreferrer&quot;&gt;TestClient&lt;/a&gt; to complete this task without modyfing the code or re-writing it?&lt;/p&gt;&#xA;&lt;p&gt;In this example the function is short, but have in mind my functions are different. I needed one month to write them all and make the connection to the Oracle db. While reading the documentation of fastAPI, I understood I should modify all the syntax to adapt it for fastAPI.&lt;/p&gt;&#xA;&lt;p&gt;So, in short can I do this with fastAPI by simply importing the functions and without changing all the functions syntax? Or do you know if is there an easier way to do it?&lt;/p&gt;&#xA;
        </summary>
    </entry>
    <entry>
        <id>https://stackoverflow.com/q/70269574</id>
        <re:rank scheme="https://stackoverflow.com">0</re:rank>
        <title type="text">How can I fall-through when matching routes in FastAPI</title>
        <category scheme="https://stackoverflow.com/tags" term="python" />
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <author>
            <name>ierdna</name>
            <uri>https://stackoverflow.com/users/1913115</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70269574/how-can-i-fall-through-when-matching-routes-in-fastapi" />
        <published>2021-12-08T03:27:25Z</published>
        <updated>2021-12-09T17:57:49Z</updated>
        <summary type="html">
            &lt;p&gt;I&#x27;m trying to deploy the FastAPI app &#x2B; front end in one Docker container, so I would not want to add NginX or another web server as it&#x27;ll complicate the setup.&lt;/p&gt;&#xA;&lt;p&gt;My routes should look like this:&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;/ &amp;lt;-- should serve index.html&#xA;/{id} &amp;lt;-- should serve index.html, but only when {id} is int&#xA;/css/* &amp;lt;-- should serve files from css directory&#xA;/... &amp;lt;-- a few other static files (e.g. /service-worker.js)&#xA;&#xA;/api/&amp;lt;whatever&amp;gt; &amp;lt;-- these are the fastAPI routes&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;So one solution is to match /{id} when it&#x27;s int and fall-through when it&#x27;s not. Alternatively if there&#x27;s a way to just serve everything as static file, except /api calls, that would work too.&lt;/p&gt;&#xA;&lt;p&gt;Currently I have something like this in my main.py:&lt;/p&gt;&#xA;&lt;pre class=&quot;lang-py prettyprint-override&quot;&gt;&lt;code&gt;@app.get(&#x27;/api/items&#x27;)&#xA;async def get_items():&#xA;    return [{&#x27;id&#x27;:1, &#x27;name&#x27;: &#x27;a&#x27;}, {&#x27;id&#x27;:2, &#x27;name&#x27;: &#x27;b&#x27;}]&#xA;&#xA;@app.get(&#x27;/{id}&#x27;)&#xA;async def root():&#xA;    with open(&#x27;html/index.html&#x27;, &#x27;r&#x27;) as f:&#xA;        return HTMLResponse(f.read())&#xA;&#xA;app.mount(&amp;quot;/&amp;quot;, StaticFiles(directory=&amp;quot;dist&amp;quot;), name=&amp;quot;static&amp;quot;)&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;But i&#x27;m getting 404 when i navigate to &amp;quot;/&amp;quot;. I&#x27;m serving it with &lt;code&gt;uvicorn main:app&lt;/code&gt;.&lt;/p&gt;&#xA;&lt;p&gt;Any help is appreciated.&lt;/p&gt;&#xA;
        </summary>
    </entry>
    <entry>
        <id>https://stackoverflow.com/q/70268226</id>
        <re:rank scheme="https://stackoverflow.com">0</re:rank>
        <title type="text">examples dict for query parameter showing warning: Could not render n, see the console</title>
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <author>
            <name>The Fool</name>
            <uri>https://stackoverflow.com/users/9208887</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70268226/examples-dict-for-query-parameter-showing-warning-could-not-render-n-see-the-c" />
        <published>2021-12-07T23:33:48Z</published>
        <updated>2021-12-07T23:41:43Z</updated>
        <summary type="html">
            &lt;p&gt;I am trying to provide &lt;a href=&quot;https://fastapi.tiangolo.com/tutorial/schema-extra-example/&quot; rel=&quot;nofollow noreferrer&quot;&gt;multiple examples&lt;/a&gt; for a query parameter.&lt;/p&gt;&#xA;&lt;pre class=&quot;lang-py prettyprint-override&quot;&gt;&lt;code&gt;def handler(&#xA;    status: str = Query(&#xA;        None,&#xA;        title=&amp;quot;Status&amp;quot;,&#xA;        description=f&amp;quot;Comma separated list. Possible values are: {&#x27;, &#x27;.join(status_list)}.&amp;quot;,&#xA;        examples={&#xA;            &amp;quot;single&amp;quot;: choice(status_list),&#xA;            &amp;quot;list&amp;quot;: &amp;quot;,&amp;quot;.join(sample(status_list, 3)),&#xA;        },&#xA;    ),&#xA;):&#xA;...&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;But it&#x27;s not showing properly in the docs page. There is a message saying:&lt;/p&gt;&#xA;&lt;blockquote&gt;&#xA;&lt;p&gt;&#x1F631; Could not render n, see the console.&lt;/p&gt;&#xA;&lt;/blockquote&gt;&#xA;&lt;p&gt;When I check the console, I see the below stacktrace.&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;root-injects.jsx:94 &#xA;TypeError: e.get is not a function&#xA;at examples-select.jsx:130&#xA;at immutable.js:3016&#xA;at immutable.js:2699&#xA;at St.__iterate (immutable.js:2206)&#xA;at zt.__iterate (immutable.js:2698)&#xA;at r.Xt.r.__iterateUncached (immutable.js:3015)&#xA;at pe (immutable.js:604)&#xA;at r.J.__iterate (immutable.js:274)&#xA;at r.forEach (immutable.js:4381)&#xA;at immutable.js:2651&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;When I use the 2 examples indivdually as single example with the keyword argument &lt;code&gt;example&lt;/code&gt;, I don&#x27;t get an error.&lt;/p&gt;&#xA;
        </summary>
    </entry>
    <entry>
        <id>https://stackoverflow.com/q/70265500</id>
        <re:rank scheme="https://stackoverflow.com">0</re:rank>
        <title type="text">POST Request from JS to FastAPI geting &quot;422 Unprocessable Entity&quot; [duplicate]</title>
        <category scheme="https://stackoverflow.com/tags" term="javascript" />
        <category scheme="https://stackoverflow.com/tags" term="reactjs" />
        <category scheme="https://stackoverflow.com/tags" term="react-native" />
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <author>
            <name>E.G. Cortes</name>
            <uri>https://stackoverflow.com/users/7747918</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70265500/post-request-from-js-to-fastapi-geting-422-unprocessable-entity" />
        <published>2021-12-07T18:50:17Z</published>
        <updated>2021-12-08T00:02:31Z</updated>
        <summary type="html">
            &lt;p&gt;I&#x27;m starting to work on a project with React and FastAPI.&lt;/p&gt;&#xA;&lt;p&gt;On the server side:&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;from fastapi import APIRouter, Request, Depends, Response, encoders&#xA;import typing&#xA;import datetime&#xA;&#xA;from app.db.session import get_db&#xA;from app.db.crud import (&#xA;    create_lead,&#xA;)&#xA;from app.db.schemas import LeadCreate&#xA;&#xA;&#xA;leads_router = r = APIRouter()&#xA;&#xA;&#xA;@r.post(&amp;quot;/leads&amp;quot;, response_model=LeadCreate)&#xA;async def lead_create(&#xA;    # request: Request,&#xA;    lead: LeadCreate,&#xA;    db=Depends(get_db),&#xA;):&#xA;    lead.datetime_insert = datetime.datetime.now()&#xA;    return create_lead(db, lead)&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;pre&gt;&lt;code&gt;from pydantic import BaseModel&#xA;import datetime&#xA;&#xA;&#xA;class LeadCreate(BaseModel):&#xA;    email: str&#xA;    source: str&#xA;    datetime_insert: datetime.datetime&#xA;&#xA;    class Config:&#xA;        orm_mode = True&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;pre&gt;&lt;code&gt;from sqlalchemy import Boolean, Column, Integer, String, DateTime&#xA;&#xA;from .session import Base&#xA;&#xA;&#xA;class Lead(Base):&#xA;    __tablename__ = &amp;quot;lead&amp;quot;&#xA;&#xA;    id = Column(Integer, primary_key=True, index=True)&#xA;    email = Column(String)&#xA;    source = Column(String)&#xA;    datetime_insert = Column(DateTime)&#xA;&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;In frontend side:&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;export const create_lead = async (email: string, source: string) =&amp;gt; {&#xA;    if (!(email.length &amp;gt; 0)) {&#xA;        throw new Error(&#x27;Email was not provided&#x27;);&#xA;    }&#xA;&#xA;    const d = {&amp;quot;email&amp;quot;: email,&#xA;               &amp;quot;source&amp;quot;: source,&#xA;               &amp;quot;datetime_insert&amp;quot;: &amp;quot;&amp;quot;,}&#xA;&#xA;    const request = new Request(&#x27;/api/v1/leads&#x27;, {&#xA;        method: &#x27;POST&#x27;,&#xA;        body: JSON.stringify(d),&#xA;    });&#xA;&#xA;    const response = await fetch(request);&#xA;&#xA;    if (response.status === 500) {&#xA;        throw new Error(&#x27;Internal server error&#x27;);&#xA;    }&#xA;&#xA;    const data = await response.json();&#xA;&#xA;    if (response.status &amp;gt; 400 &amp;amp;&amp;amp; response.status &amp;lt; 500) {&#xA;        if (data.detail) {&#xA;          throw data.detail;&#xA;        }&#xA;        throw data;&#xA;    }&#xA;&#xA;    return data;&#xA;};&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;However, I&#x27;m getting the following error in the backend log:&#xA;&lt;code&gt;&amp;quot;POST /api/v1/leads HTTP/1.0&amp;quot; 422 Unprocessable Entity&lt;/code&gt;&lt;/p&gt;&#xA;&lt;p&gt;I have already tried to use &lt;code&gt;FormData&lt;/code&gt;. I think it is related to the data structure, where the frontend side is sending something different than the expected by server-side.&lt;/p&gt;&#xA;&lt;p&gt;&lt;a href=&quot;https://i.stack.imgur.com/k9G5W.png&quot; rel=&quot;nofollow noreferrer&quot;&gt;&lt;img src=&quot;https://i.stack.imgur.com/k9G5W.png&quot; alt=&quot;enter image description here&quot; /&gt;&lt;/a&gt;&lt;/p&gt;&#xA;
        </summary>
    </entry>
    <entry>
        <id>https://stackoverflow.com/q/70265343</id>
        <re:rank scheme="https://stackoverflow.com">0</re:rank>
        <title type="text">python fastAPI Server. How to extend connection timeout</title>
        <category scheme="https://stackoverflow.com/tags" term="python" />
        <category scheme="https://stackoverflow.com/tags" term="flask" />
        <category scheme="https://stackoverflow.com/tags" term="https" />
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <author>
            <name>Zohar81</name>
            <uri>https://stackoverflow.com/users/4333809</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70265343/python-fastapi-server-how-to-extend-connection-timeout" />
        <published>2021-12-07T18:36:50Z</published>
        <updated>2021-12-07T19:41:44Z</updated>
        <summary type="html">
            &lt;p&gt;I&#x27;m using fastAPI python framework to build a simple POST/GET https server.&#xA;On the client side, i send heartbeat POST messages every 10 seconds and i&#x27;d like to keep my connection open during this period.&lt;/p&gt;&#xA;&lt;p&gt;However, for some reason I see that every new heartbeat, my connection get disconnected by the peer, so I need to re-establish it. If the idle period between 2 consecutive keepalives is 1 second, the Connection remains active, and can be reused.&lt;/p&gt;&#xA;&lt;p&gt;I&#x27;m using &lt;code&gt;HTTP/1.1&lt;/code&gt; with &lt;code&gt;Connection: keep-alive&lt;/code&gt;, but it is entirely up to the server how long it will keep the connection alive, and I&#x27;m looking for a way to extend this timeout to ~15 seconds. is there any suitable way to do it ? or even just make the server print proper log message when it decide to disconnect the client peer ...&lt;/p&gt;&#xA;&lt;p&gt;P.S. in order to start the server I&#x27;m using the following command, Perhaps it need to be modified ?&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;uvicorn main:app --port 44444 --host 0.0.0.0 --reload  --ssl-keyfile ./key.pem &#xA;--ssl-certfile ./certificate.pem --log-level debug&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;
        </summary>
    </entry>
    <entry>
        <id>https://stackoverflow.com/q/70258315</id>
        <re:rank scheme="https://stackoverflow.com">0</re:rank>
        <title type="text">SQLAlchemy - sqlalchemy.exc.ResourceClosedError: This result object is closed</title>
        <category scheme="https://stackoverflow.com/tags" term="python" />
        <category scheme="https://stackoverflow.com/tags" term="async-await" />
        <category scheme="https://stackoverflow.com/tags" term="sqlalchemy" />
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <category scheme="https://stackoverflow.com/tags" term="pydantic" />
        <author>
            <name>kkg</name>
            <uri>https://stackoverflow.com/users/16444346</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70258315/sqlalchemy-sqlalchemy-exc-resourceclosederror-this-result-object-is-closed" />
        <published>2021-12-07T10:13:56Z</published>
        <updated>2021-12-07T10:13:56Z</updated>
        <summary type="html">
            &lt;p&gt;The project is made up of several modules.&lt;/p&gt;&#xA;&lt;blockquote&gt;&#xA;&lt;p&gt;db/config.py&lt;/p&gt;&#xA;&lt;/blockquote&gt;&#xA;&lt;pre&gt;&lt;code&gt;from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession&#xA;from sqlalchemy.orm import declarative_base ,sessionmaker&#xA;&#xA;&#xA;DATABASE_URL = &#x27;sqlite&#x2B;aiosqlite:///./database.db&#x27;&#xA;&#xA;engine = create_async_engine(DATABASE_URL, future=True, echo=True)&#xA;async_session = sessionmaker(bind=engine, expire_on_commit=False, class_=AsyncSession)&#xA;Base = declarative_base()&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;blockquote&gt;&#xA;&lt;p&gt;db/models/user.py&lt;/p&gt;&#xA;&lt;/blockquote&gt;&#xA;&lt;pre&gt;&lt;code&gt;from datetime import datetime&#xA;&#xA;from sqlalchemy import Column, Integer, String, DateTime, Boolean&#xA;from sqlalchemy.orm import relationship&#xA;&#xA;from passlib.context import CryptContext&#xA;&#xA;from db.config import Base&#xA;from db.models.post import Post&#xA;&#xA;&#xA;class User(Base):&#xA;    __tablename__ = &#x27;users&#x27;&#xA;&#xA;    hasher = CryptContext(schemes=[&amp;quot;bcrypt&amp;quot;])&#xA;&#xA;    id = Column(Integer, primary_key=True)&#xA;    email = Column(String(320), unique=True, nullable=False)&#xA;    hashed_password = Column(String(128), nullable=False)&#xA;    is_active = Column(Boolean, default=True)&#xA;&#xA;    posts = relationship(&amp;quot;Post&amp;quot;, back_populates=&amp;quot;owner&amp;quot;)&#xA;    comments = relationship(&amp;quot;Comment&amp;quot;, back_populates=&amp;quot;owner&amp;quot;)&#xA;&#xA;    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)&#xA;    modified_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)&#xA;&#xA;    def hash_password(self, plaintext_password):&#xA;        self.hashed_password = self.hasher.hash(plaintext_password)&#xA;&#xA;    def verify_password(self, plaintext_password):&#xA;        return self.hasher.verify(plaintext_password, self.hashed_password)&#xA;&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;blockquote&gt;&#xA;&lt;p&gt;schemas/user_schema.py&lt;/p&gt;&#xA;&lt;/blockquote&gt;&#xA;&lt;pre&gt;&lt;code&gt;from datetime import datetime&#xA;&#xA;from pydantic import BaseModel&#xA;&#xA;&#xA;class UserBase(BaseModel):&#xA;    email: str&#xA;&#xA;&#xA;class UserCreate(UserBase):&#xA;    password: str&#xA;&#xA;&#xA;class UserResponseBody(BaseModel):&#xA;    id: int&#xA;    email: str&#xA;    is_active: bool&#xA;    created_at: datetime&#xA;    modified_at: datetime&#xA;&#xA;    class Config:&#xA;        orm_mode = True&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;blockquote&gt;&#xA;&lt;p&gt;db/dals/user_dal.py&lt;/p&gt;&#xA;&lt;/blockquote&gt;&#xA;&lt;pre&gt;&lt;code&gt;from sqlalchemy import update&#xA;from sqlalchemy.future import select&#xA;from sqlalchemy.orm import Session&#xA;&#xA;from db.models.user import User&#xA;from schemas import user_schema&#xA;&#xA;&#xA;class UserDAL:&#xA;    def __init__(self, db_session: Session):&#xA;        self.db_session = db_session&#xA;&#xA;    async def create_user(self, user: user_schema.UserCreate):&#xA;        new_user = User(email=user.email)&#xA;        new_user.hash_password(user.password)&#xA;        self.db_session.add(new_user)&#xA;        await self.db_session.commit()&#xA;&#xA;    async def get_user(self, user_id: int):&#xA;        query = await self.db_session.execute(select(User).where(User.id == user_id))&#xA;        print(query.first())&#xA;        return query.first()&#xA;&#xA;    async def get_user_by_email(self, email: str):&#xA;        query = await self.db_session.execute(select(User).where(User.email == email))&#xA;        return query.first()&#xA;&#xA;    async def get_users(self, skip: int = 0, limit: int = 100):&#xA;        query = await self.db_session.execute(select(User).offset(skip).limit(limit).order_by(User.id))&#xA;        return query.fetchall()&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;blockquote&gt;&#xA;&lt;p&gt;dependencies.py&lt;/p&gt;&#xA;&lt;/blockquote&gt;&#xA;&lt;pre&gt;&lt;code&gt;from db.config import async_session&#xA;from db.dals.user_dal import UserDAL&#xA;from db.dals.post_dal import PostDAL&#xA;from db.dals.comment_dal import CommentDAL&#xA;from db.dals.reply_dal import ReplyDAL&#xA;&#xA;&#xA;async def get_user_dal():&#xA;    async with async_session() as session:&#xA;        async with session.begin():&#xA;            yield UserDAL(session)&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;blockquote&gt;&#xA;&lt;p&gt;routers/user_router.py&lt;/p&gt;&#xA;&lt;/blockquote&gt;&#xA;&lt;pre&gt;&lt;code&gt;from typing import List&#xA;&#xA;from fastapi import APIRouter, Depends, FastAPI&#xA;from fastapi.exceptions import HTTPException&#xA;&#xA;from db.dals.user_dal import UserDAL&#xA;from db.models.user import User&#xA;from schemas import user_schema&#xA;from dependencies import get_user_dal&#xA;&#xA;router = APIRouter(prefix=&amp;quot;/users&amp;quot;)&#xA;&#xA;@router.post(&amp;quot;/&amp;quot;, response_model=user_schema.UserResponseBody)&#xA;async def create_user(user: user_schema.UserCreate, user_dal: UserDAL = Depends(get_user_dal)):&#xA;    db_user = await user_dal.get_user_by_email(email=user.email)&#xA;    if db_user:&#xA;        raise HTTPException(status_code=400, detail=&amp;quot;Email already registered&amp;quot;)&#xA;    await user_dal.create_user(user=user)&#xA;&#xA;@router.get(&amp;quot;/{user_id}&amp;quot;, response_model=user_schema.UserResponseBody)&#xA;async def get_user(user_id: int, user_dal: UserDAL = Depends(get_user_dal)):&#xA;    db_user =  await user_dal.get_user(user_id=user_id)&#xA;    if db_user is None:&#xA;        raise HTTPException(status_code=404, detail=&amp;quot;User not found&amp;quot;)&#xA;    return db_user&#xA;&#xA;@router.get(&amp;quot;/&amp;quot;, response_model=List[user_schema.UserResponseBody])&#xA;async def get_users(skip: int = 0, limit: int = 100, user_dal: UserDAL = Depends(get_user_dal)):&#xA;    db_users = await user_dal.get_users(skip=skip, limit=limit)&#xA;    return db_users&#xA;&#xA;@router.get(&amp;quot;/{user_email}&amp;quot;, response_model=user_schema.UserResponseBody)&#xA;async def get_user_by_email(user_email ,user_dal: UserDAL = Depends(get_user_dal)):&#xA;    db_user =  await user_dal.get_user_by_email(email=user_email)&#xA;    if db_user is None:&#xA;        raise HTTPException(status_code=404, detail=&amp;quot;User not found&amp;quot;)&#xA;    return db_user&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;blockquote&gt;&#xA;&lt;p&gt;main.py&lt;/p&gt;&#xA;&lt;/blockquote&gt;&#xA;&lt;pre&gt;&lt;code&gt;import uvicorn&#xA;from fastapi import FastAPI&#xA;&#xA;from db.config import engine, Base&#xA;from routers import user_router&#xA;&#xA;app = FastAPI()&#xA;app.include_router(user_router.router)&#xA;&#xA;&#xA;@app.on_event(&amp;quot;startup&amp;quot;)&#xA;async def startup():&#xA;    # create db tables&#xA;    async with engine.begin() as conn:&#xA;        await conn.run_sync(Base.metadata.drop_all)&#xA;        await conn.run_sync(Base.metadata.create_all)&#xA;&#xA;&#xA;if __name__ == &#x27;__main__&#x27;:&#xA;    uvicorn.run(&#x27;main:app&#x27;, host=&#x27;127.0.0.1&#x27;, port=8000, reload=True)&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;It also returns this error when I try to get all users from a non empty database.&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;2021-12-07 10:06:13,138 INFO sqlalchemy.engine.Engine BEGIN (implicit)&#xA;2021-12-07 10:06:13,165 INFO sqlalchemy.engine.Engine SELECT users.id, users.email, users.hashed_password, users.is_active, users.created_at, users.modified_at &#xA;FROM users &#xA;WHERE users.email = ?&#xA;2021-12-07 10:06:13,165 INFO sqlalchemy.engine.Engine [generated in 0.00031s] (&#x27;string&#x27;,)&#xA;2021-12-07 10:06:13,483 INFO sqlalchemy.engine.Engine INSERT INTO users (email, hashed_password, is_active, created_at, modified_at) VALUES (?, ?, ?, ?, ?)&#xA;2021-12-07 10:06:13,483 INFO sqlalchemy.engine.Engine [generated in 0.00026s] (&#x27;string&#x27;, &#x27;$2b$12$dcEXt.Ow/8vsWVPTHOeGEOA3T7Kf/pUs0ncAcWOcmrtkFuG/c/ZQC&#x27;, 1, &#x27;2021-12-07 10:06:13.483391&#x27;, &#x27;2021-12-07 10:06:13.483397&#x27;)&#xA;2021-12-07 10:06:13,485 INFO sqlalchemy.engine.Engine COMMIT&#xA;INFO:     127.0.0.1:56114 - &amp;quot;POST /users/ HTTP/1.1&amp;quot; 200 OK&#xA;2021-12-07 10:06:27,149 INFO sqlalchemy.engine.Engine BEGIN (implicit)&#xA;2021-12-07 10:06:27,151 INFO sqlalchemy.engine.Engine SELECT users.id, users.email, users.hashed_password, users.is_active, users.created_at, users.modified_at &#xA;FROM users ORDER BY users.id&#xA; LIMIT ? OFFSET ?&#xA;2021-12-07 10:06:27,151 INFO sqlalchemy.engine.Engine [generated in 0.00032s] (100, 0)&#xA;INFO:     127.0.0.1:56122 - &amp;quot;GET /users/?skip=0&amp;amp;limit=100 HTTP/1.1&amp;quot; 500 Internal Server Error&#xA;2021-12-07 10:06:27,153 INFO sqlalchemy.engine.Engine ROLLBACK&#xA;ERROR:    Exception in ASGI application&#xA;Traceback (most recent call last):&#xA;  File &amp;quot;/home/bit/.cache/pypoetry/virtualenvs/asyncdb-XW20QW2x-py3.8/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py&amp;quot;, line 373, in run_asgi&#xA;    result = await app(self.scope, self.receive, self.send)&#xA;  File &amp;quot;/home/bit/.cache/pypoetry/virtualenvs/asyncdb-XW20QW2x-py3.8/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py&amp;quot;, line 75, in __call__&#xA;    return await self.app(scope, receive, send)&#xA;  File &amp;quot;/home/bit/.cache/pypoetry/virtualenvs/asyncdb-XW20QW2x-py3.8/lib/python3.8/site-packages/fastapi/applications.py&amp;quot;, line 208, in __call__&#xA;    await super().__call__(scope, receive, send)&#xA;  File &amp;quot;/home/bit/.cache/pypoetry/virtualenvs/asyncdb-XW20QW2x-py3.8/lib/python3.8/site-packages/starlette/applications.py&amp;quot;, line 112, in __call__&#xA;    await self.middleware_stack(scope, receive, send)&#xA;  File &amp;quot;/home/bit/.cache/pypoetry/virtualenvs/asyncdb-XW20QW2x-py3.8/lib/python3.8/site-packages/starlette/middleware/errors.py&amp;quot;, line 181, in __call__&#xA;    raise exc&#xA;  File &amp;quot;/home/bit/.cache/pypoetry/virtualenvs/asyncdb-XW20QW2x-py3.8/lib/python3.8/site-packages/starlette/middleware/errors.py&amp;quot;, line 159, in __call__&#xA;    await self.app(scope, receive, _send)&#xA;  File &amp;quot;/home/bit/.cache/pypoetry/virtualenvs/asyncdb-XW20QW2x-py3.8/lib/python3.8/site-packages/starlette/exceptions.py&amp;quot;, line 82, in __call__&#xA;    raise exc&#xA;  File &amp;quot;/home/bit/.cache/pypoetry/virtualenvs/asyncdb-XW20QW2x-py3.8/lib/python3.8/site-packages/starlette/exceptions.py&amp;quot;, line 71, in __call__&#xA;    await self.app(scope, receive, sender)&#xA;  File &amp;quot;/home/bit/.cache/pypoetry/virtualenvs/asyncdb-XW20QW2x-py3.8/lib/python3.8/site-packages/starlette/routing.py&amp;quot;, line 656, in __call__&#xA;    await route.handle(scope, receive, send)&#xA;  File &amp;quot;/home/bit/.cache/pypoetry/virtualenvs/asyncdb-XW20QW2x-py3.8/lib/python3.8/site-packages/starlette/routing.py&amp;quot;, line 259, in handle&#xA;    await self.app(scope, receive, send)&#xA;  File &amp;quot;/home/bit/.cache/pypoetry/virtualenvs/asyncdb-XW20QW2x-py3.8/lib/python3.8/site-packages/starlette/routing.py&amp;quot;, line 61, in app&#xA;    response = await func(request)&#xA;  File &amp;quot;/home/bit/.cache/pypoetry/virtualenvs/asyncdb-XW20QW2x-py3.8/lib/python3.8/site-packages/fastapi/routing.py&amp;quot;, line 234, in app&#xA;    response_data = await serialize_response(&#xA;  File &amp;quot;/home/bit/.cache/pypoetry/virtualenvs/asyncdb-XW20QW2x-py3.8/lib/python3.8/site-packages/fastapi/routing.py&amp;quot;, line 137, in serialize_response&#xA;    raise ValidationError(errors, field.type_)&#xA;pydantic.error_wrappers.ValidationError: 5 validation errors for UserResponseBody&#xA;response -&amp;gt; 0 -&amp;gt; id&#xA;  field required (type=value_error.missing)&#xA;response -&amp;gt; 0 -&amp;gt; email&#xA;  field required (type=value_error.missing)&#xA;response -&amp;gt; 0 -&amp;gt; is_active&#xA;  field required (type=value_error.missing)&#xA;response -&amp;gt; 0 -&amp;gt; created_at&#xA;  field required (type=value_error.missing)&#xA;response -&amp;gt; 0 -&amp;gt; modified_at&#xA;  field required (type=value_error.missing)&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;The response body returns null when I create a new user instead of the UserResponseBody pydantic object.&lt;/p&gt;&#xA;&lt;p&gt;Trying to get a user by email returns a (422) Error: Unprocessable Entity.&lt;/p&gt;&#xA;
        </summary>
    </entry>
    <entry>
        <id>https://stackoverflow.com/q/70257170</id>
        <re:rank scheme="https://stackoverflow.com">0</re:rank>
        <title type="text">How to debug Fastapi openapi generation error</title>
        <category scheme="https://stackoverflow.com/tags" term="python" />
        <category scheme="https://stackoverflow.com/tags" term="swagger" />
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <category scheme="https://stackoverflow.com/tags" term="openapi-generator" />
        <author>
            <name>Eugene</name>
            <uri>https://stackoverflow.com/users/8668595</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70257170/how-to-debug-fastapi-openapi-generation-error" />
        <published>2021-12-07T08:46:00Z</published>
        <updated>2021-12-07T08:46:00Z</updated>
        <summary type="html">
            &lt;p&gt;I spend some time going over this error but had no success.&lt;/p&gt;&#xA;&lt;blockquote&gt;&#xA;&lt;p&gt;File &amp;quot;C:\Users\ebara.conda\envs\asci\lib\site-packages\fastapi\openapi\utils.py&amp;quot;, line 388, in get_openapi&#xA;flat_models=flat_models, model_name_map=model_name_map&lt;/p&gt;&#xA;&lt;/blockquote&gt;&#xA;&lt;blockquote&gt;&#xA;&lt;p&gt;File &amp;quot;C:\Users\ebara.conda\envs\asci\lib\site-packages\fastapi\utils.py&amp;quot;, line 28, in get_model_definitions&#xA;model_name = model_name_map[model]&lt;/p&gt;&#xA;&lt;/blockquote&gt;&#xA;&lt;blockquote&gt;&#xA;&lt;p&gt;KeyError: &amp;lt;class &#x27;pydantic.main.Body_login_access_token_api_v1_login_access_token_post&#x27;&amp;gt;&lt;/p&gt;&#xA;&lt;/blockquote&gt;&#xA;&lt;p&gt;The problem is that I&#x27;m trying to build a project with user authentication from OpenAPI form to create new users in database.&lt;/p&gt;&#xA;&lt;p&gt;I&#x27;ve used backend part of this template project &lt;a href=&quot;https://github.com/tiangolo/full-stack-fastapi-postgresql&quot; rel=&quot;nofollow noreferrer&quot;&gt;https://github.com/tiangolo/full-stack-fastapi-postgresql&lt;/a&gt;&lt;/p&gt;&#xA;&lt;p&gt;Everything works except for Authentication like &lt;a href=&quot;https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/490c554e23343eec0736b06e59b2108fdd057fdc/%7B%7Bcookiecutter.project_slug%7D%7D/backend/app/app/api/api_v1/endpoints/login.py#L22&quot; rel=&quot;nofollow noreferrer&quot;&gt;here&lt;/a&gt;.&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;@router.post(&amp;quot;/login/access-token&amp;quot;, response_model=schemas.Token)&#xA;def login_access_token(&#xA;    db: Session = Depends(deps.get_db), form_data: OAuth2PasswordRequestForm = Depends()) -&amp;gt; Any:&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;When I add this part &lt;code&gt;form_data: OAuth2PasswordRequestForm = Depends()&lt;/code&gt; - and go to /docs page - this error appears (Failed to load API definition. Fetch error. Internal Server Error /openapi.json)&lt;/p&gt;&#xA;&lt;p&gt;&lt;a href=&quot;https://i.stack.imgur.com/gxPjs.png&quot; rel=&quot;nofollow noreferrer&quot;&gt;&lt;img src=&quot;https://i.stack.imgur.com/gxPjs.png&quot; alt=&quot;error picture&quot; /&gt;&lt;/a&gt; .&lt;/p&gt;&#xA;&lt;p&gt;The server itself runs in normal mode, but it can&#x27;t load the open API. If I remove the aforementioned formdata part - then everything works smoothly, but without Authorisation. I tried to debug it, but I have no success. I think it might be connected to a dependency graph or some start-up issues, but have no guess how to trace it back.&lt;/p&gt;&#xA;&lt;p&gt;Any ideas?&lt;/p&gt;&#xA;
        </summary>
    </entry>
    <entry>
        <id>https://stackoverflow.com/q/70250068</id>
        <re:rank scheme="https://stackoverflow.com">1</re:rank>
        <title type="text">With FastAPI, How to add charset to content-type (media-type) on request header on OpenAPI (Swagger) doc?</title>
        <category scheme="https://stackoverflow.com/tags" term="python-3.x" />
        <category scheme="https://stackoverflow.com/tags" term="swagger" />
        <category scheme="https://stackoverflow.com/tags" term="openapi" />
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <author>
            <name>Alumuko</name>
            <uri>https://stackoverflow.com/users/6900431</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70250068/with-fastapi-how-to-add-charset-to-content-type-media-type-on-request-header" />
        <published>2021-12-06T18:19:50Z</published>
        <updated>2021-12-06T18:19:50Z</updated>
        <summary type="html">
            &lt;p&gt;With FastAPI, How to  add charset to content-type (media-type) on request header on OpenAPI (Swagger) doc?&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;@app.post(&amp;quot;/&amp;quot;)&#xA;def post_hello(username: str = Form(...)):&#xA;   return {&amp;quot;Hello&amp;quot;: username}&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;OpenAPI (http:///docs) shows &amp;quot;&lt;em&gt;application/x-www-form-urlencoded&lt;/em&gt;&amp;quot;.&lt;/p&gt;&#xA;&lt;p&gt;&lt;a href=&quot;https://i.stack.imgur.com/bJ7Ip.png&quot; rel=&quot;nofollow noreferrer&quot;&gt;&lt;img src=&quot;https://i.stack.imgur.com/bJ7Ip.png&quot; alt=&quot;openapi doc&quot; /&gt;&lt;/a&gt;&lt;/p&gt;&#xA;&lt;p&gt;I tried to change like:&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;def post_hello(username: str = Form(..., media_type=&amp;quot;application/x-www-form-urlencoded; charset=cp932&amp;quot;)):&#xA;   return {&amp;quot;Hello&amp;quot;: &amp;quot;World!&amp;quot;, &amp;quot;userName&amp;quot;: username}&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;but not be add &lt;em&gt;charset=cp932&lt;/em&gt;&lt;/p&gt;&#xA;&lt;p&gt;I want to set &amp;quot;&lt;em&gt;application/x-www-form-urlencoded; charset=cp932&lt;/em&gt;&amp;quot; to Content-Type on Request.&#xA;And I want to get &lt;em&gt;username&lt;/em&gt; decoded by the charset.&lt;/p&gt;&#xA;
        </summary>
    </entry>
    <entry>
        <id>https://stackoverflow.com/q/70246576</id>
        <re:rank scheme="https://stackoverflow.com">2</re:rank>
        <title type="text">FastAPI, Pydantic joinedload instead of lazy</title>
        <category scheme="https://stackoverflow.com/tags" term="python" />
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <category scheme="https://stackoverflow.com/tags" term="pydantic" />
        <category scheme="https://stackoverflow.com/tags" term="starlette" />
        <author>
            <name>Mathias Clausen</name>
            <uri>https://stackoverflow.com/users/17603651</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70246576/fastapi-pydantic-joinedload-instead-of-lazy" />
        <published>2021-12-06T13:52:39Z</published>
        <updated>2021-12-06T13:52:39Z</updated>
        <summary type="html">
            &lt;p&gt;I am trying to optimize on the performance of my models, however I can see that FastAPI is loading the relations of my model PurchaseOrderPart as lazy.. This is causing a n&#x2B;1 problem, which is a big problem.&#xA;Is there any way I can make FastAPI load the relations as joined? When I am not using the response model parameter I get most of the data I need, but not all the relations.&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;class PurchaseOrderPart(Base):&#xA;    __tablename__ = &amp;quot;purchase_order_part&amp;quot;&#xA;    id = Column(BigInteger, primary_key=True, index=True)&#xA;    quantity = Column(Float)&#xA;    ordered_at = Column(DateTime, nullable=True)&#xA;    expected_at = Column(DateTime, nullable=True)&#xA;    confirmed_at = Column(DateTime, nullable=True)&#xA;    delivered_at = Column(DateTime, nullable=True)&#xA;    invoiced_at = Column(DateTime, nullable=True)&#xA;    price_dkk = Column(BigInteger, server_default=&amp;quot;0&amp;quot;)&#xA;    deviation = Column(String, nullable=True)&#xA;    supplier_part_id = Column(BigInteger, ForeignKey(&amp;quot;supplier_part.id&amp;quot;))&#xA;    supplier_id = Column(BigInteger, ForeignKey(&amp;quot;supplier.id&amp;quot;))&#xA;    project_reference_id = Column(BigInteger, ForeignKey(&#xA;        &amp;quot;project_reference.id&amp;quot;), nullable=True)&#xA;    stockpile_part_id = Column(BigInteger, ForeignKey(&#xA;        &amp;quot;stockpile_part.id&amp;quot;), nullable=True)&#xA;    purchase_order_id = Column(BigInteger, ForeignKey(&#xA;        &amp;quot;purchase_order.id&amp;quot;), nullable=True)&#xA;    created_at = Column(DateTime, server_default=func.now())&#xA;    updated_at = Column(DateTime, server_default=func.now(),&#xA;                        onupdate=func.current_timestamp())&#xA;&#xA;    supplier_part = relationship(&#xA;        &amp;quot;SupplierPart&amp;quot;, uselist=False, foreign_keys=[supplier_part_id], lazy=&amp;quot;selectin&amp;quot;)&#xA;    supplier = relationship(&amp;quot;Supplier&amp;quot;, uselist=False,&#xA;                            foreign_keys=[supplier_id], lazy=&amp;quot;selectin&amp;quot;)&#xA;    project_reference = relationship(&#xA;        &amp;quot;ProjectReference&amp;quot;, uselist=False, foreign_keys=[project_reference_id], lazy=&amp;quot;selectin&amp;quot;)&#xA;    stockpile_part = relationship(&#xA;        &amp;quot;StockpilePart&amp;quot;, uselist=False, foreign_keys=[stockpile_part_id], lazy=&amp;quot;selectin&amp;quot;)&#xA;    purchase_order = relationship(&#xA;        &amp;quot;PurchaseOrder&amp;quot;, uselist=False, foreign_keys=[purchase_order_id], lazy=&amp;quot;selectin&amp;quot;)&#xA;    purchase_order_part_notes = relationship(&#xA;        &amp;quot;PurchaseOrderPartNote&amp;quot;, back_populates=&amp;quot;purchase_order_part&amp;quot;, lazy=&amp;quot;selectin&amp;quot;)`&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;pre&gt;&lt;code&gt;&#xA;class PurchaseOrderPartRelation(PurchaseOrderPart):&#xA;    purchase_order_part_notes: Optional[List[&amp;quot;PurchaseOrderPartNote&amp;quot;]] = None&#xA;    supplier: Optional[SupplierBase] = None&#xA;    supplier_part: Optional[SupplierPart] = None&#xA;    purchase_order: Optional[PurchaseOrder] = None&#xA;    project_reference: Optional[ProjectReference] = None&#xA;    stockpile_part: Optional[StockpilePartRelation] = None&#xA;    part: Optional[&amp;quot;Part&amp;quot;]&#xA;&#xA;&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;pre&gt;&lt;code&gt;#################################&#xA;#    Not Confirmed&#xA;#################################&#xA;@router.get(&#xA;    &amp;quot;/not_confirmed&amp;quot;,&#xA;    summary=&amp;quot;List all purchase order parts that are ordered but not confirmed&amp;quot;,&#xA;    status_code=status.HTTP_200_OK,&#xA;)&#xA;def get_not_confirmed_parts(request: Request, end_days_from_now: int = 7,&#xA;                                  filter_and: Optional[List[str]] = Query(None),&#xA;                                  filter_or: Optional[List[str]] = Query(None),&#xA;                                  sort: Optional[List[str]] = Query(None),&#xA;                                  page: int = 1,&#xA;                                  size: int = 1000,&#xA;                                  current_user: User = Depends(&#xA;                                      get_current_user),&#xA;                                  db: Session = Depends(get_db)):&#xA;&#xA;    with tracer.start_span(&amp;quot;traces for not confirmed parts&amp;quot;) as current_span:&#xA;&#xA;        query = db.query(models.PurchaseOrderPart, models.SupplierPart, models.Part).\&#xA;            filter(and_(&#xA;                models.PurchaseOrderPart.confirmed_at.is_(None),&#xA;                models.PurchaseOrderPart.delivered_at.is_(None),&#xA;                models.PurchaseOrderPart.ordered_at &amp;lt;= ordered_date,&#xA;                models.PurchaseOrderPart.supplier_part_id == models.SupplierPart.id,&#xA;                models.Part.primary_supplier_part_id == models.SupplierPart.id&#xA;                ))&#xA;&#xA;&#xA;        # logger.debug(str(query))&#xA;&#xA;    # return query&#xA;&#xA;    with tracer.start_span(&amp;quot;get filtered page trace&amp;quot;) as current_span:&#xA;        results = get_filtered_page(&#xA;            db,&#xA;            query,&#xA;            filter_or,&#xA;            filter_and,&#xA;            sort,&#xA;            page,&#xA;            size)&#xA;    return results&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;
        </summary>
    </entry>
    <entry>
        <id>https://stackoverflow.com/q/70243528</id>
        <re:rank scheme="https://stackoverflow.com">1</re:rank>
        <title type="text">Propagate top-level span ID&#x27;s in OpenTelemetry</title>
        <category scheme="https://stackoverflow.com/tags" term="python" />
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <category scheme="https://stackoverflow.com/tags" term="open-telemetry" />
        <category scheme="https://stackoverflow.com/tags" term="distributed-tracing" />
        <author>
            <name>iLikeBreakfast</name>
            <uri>https://stackoverflow.com/users/1795229</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70243528/propagate-top-level-span-ids-in-opentelemetry" />
        <published>2021-12-06T09:48:19Z</published>
        <updated>2021-12-10T02:23:15Z</updated>
        <summary type="html">
            &lt;p&gt;I&#x27;m trying to get OpenTelemetry tracing working with FastAPI and Requests. Currently, my setup looks like this:&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;import requests&#xA;from opentelemetry.baggage.propagation import W3CBaggagePropagator&#xA;from opentelemetry.propagators.composite import CompositePropagator&#xA;from fastapi import FastAPI&#xA;from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor&#xA;from opentelemetry.instrumentation.requests import RequestsInstrumentor&#xA;from opentelemetry.propagate import set_global_textmap&#xA;from opentelemetry.propagators.b3 import B3MultiFormat&#xA;from opentelemetry.trace.propagation.tracecontext import TraceContextTextMapPropagator&#xA;&#xA;set_global_textmap(CompositePropagator([B3MultiFormat(), TraceContextTextMapPropagator(), W3CBaggagePropagator()]))&#xA;&#xA;app = FastAPI()&#xA;&#xA;FastAPIInstrumentor.instrument_app(app)&#xA;RequestsInstrumentor().instrument()&#xA;&#xA;@app.get(&amp;quot;/&amp;quot;)&#xA;async def get_things():&#xA;    r = requests.get(&amp;quot;http://localhost:8081&amp;quot;)&#xA;&#xA;    return {&#xA;        &amp;quot;Hello&amp;quot;: &amp;quot;world&amp;quot;,&#xA;        &amp;quot;result&amp;quot;: r.json()&#xA;    }&#xA;&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;The &lt;code&gt;/&lt;/code&gt; endpoint just does a GET to another service that looks basically like this one, just with some middleware to log the incoming headers.&lt;/p&gt;&#xA;&lt;p&gt;If I send a request like this (httpie format),&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;http :8000 &#x27;x-b3-traceid: f8c83f4b5806299983da51de66d9a242&#x27; &#x27;x-b3-spanid: ba24f165998dfd8f&#x27; &#x27;x-b3-sampled: 1&#x27;&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;I expect that the downstream service, i.e. the one being requested by &lt;code&gt;requests.get(&amp;quot;http://localhost:8081&amp;quot;)&lt;/code&gt;, to receive headers that look something like&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;{&#xA;  &amp;quot;x-b3-traceid&amp;quot;: &amp;quot;f8c83f4b5806299983da51de66d9a242&amp;quot;,&#xA;  &amp;quot;x-b3-spanid&amp;quot;: &amp;quot;xxxxxxx&amp;quot;,  # some generated value from the upstream service&#xA;  &amp;quot;x-b3-parentspanid&amp;quot;: &amp;quot;ba24f165998dfd8f&amp;quot;, &#xA;  &amp;quot;x-b3-sampled&amp;quot;: &amp;quot;1&amp;quot;&#xA;}&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;But what I&#x27;m getting is basically exactly what I sent to the upstream service:&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;{&#xA;  &amp;quot;x-b3-traceid&amp;quot;: &amp;quot;f8c83f4b5806299983da51de66d9a242&amp;quot;,&#xA;  &amp;quot;x-b3-spanid&amp;quot;: &amp;quot;ba24f165998dfd8f&amp;quot;,&#xA;  &amp;quot;x-b3-sampled&amp;quot;: &amp;quot;1&amp;quot;&#xA;}&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;I must be missing something obvious, but can&#x27;t seem to figure out exactly what.&lt;/p&gt;&#xA;&lt;p&gt;Sending a W3C &lt;code&gt;traceparent&lt;/code&gt; header results in the same exact situation (just with &lt;code&gt;traceparent&lt;/code&gt; in the headers that are received downstream). Any pointers would be appreciated.&lt;/p&gt;&#xA;&lt;p&gt;EDIT - I&#x27;m not using any exporters, as in our environment, Istio is configured to export the traces. So we just care about the HTTP traces for now.&lt;/p&gt;&#xA;
        </summary>
    </entry>
    <entry>
        <id>https://stackoverflow.com/q/70240373</id>
        <re:rank scheme="https://stackoverflow.com">1</re:rank>
        <title type="text">How to add new dict to list of dict with SQLAlchemy</title>
        <category scheme="https://stackoverflow.com/tags" term="python" />
        <category scheme="https://stackoverflow.com/tags" term="sqlalchemy" />
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <author>
            <name>T_Ner</name>
            <uri>https://stackoverflow.com/users/12465949</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70240373/how-to-add-new-dict-to-list-of-dict-with-sqlalchemy" />
        <published>2021-12-06T02:44:41Z</published>
        <updated>2021-12-06T13:45:46Z</updated>
        <summary type="html">
            &lt;p&gt;Let&#x27;s say this is a sample json.&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;{&#xA;  &amp;quot;id&amp;quot;: 1,&#xA;  &amp;quot;details&amp;quot;: [&#xA;    {&#xA;      &amp;quot;a&amp;quot;: &amp;quot;100&amp;quot;,&#xA;    }&#xA;  ]&#xA;}&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;The result that i want is add &lt;code&gt;{&#x27;b&#x27;: &#x27;200&#x27;}&lt;/code&gt; to details and it will look like this.&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;{&#xA;  &amp;quot;id&amp;quot;: 1,&#xA;  &amp;quot;details&amp;quot;: [&#xA;    {&#xA;      &amp;quot;a&amp;quot;: &amp;quot;100&amp;quot;,&#xA;    },&#xA;    {&#xA;      &amp;quot;b&amp;quot;: &amp;quot;200&amp;quot;,&#xA;    },&#xA;  ]&#xA;}&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&lt;p&gt;In my file, I have tried many times but it still doesn&#x27;t work So, how to add dict with sqlalchemy&lt;/p&gt;&#xA;&lt;pre&gt;&lt;code&gt;class Models(Base):&#xA;    __tablename__ = &#x27;Table&#x27;&#xA;    id = Column(Integer, primary_key=True)&#xA;    details = Column(JSONB, nullable=False, server_default=&#x27;[]&#x27;)&#xA;&#xA;&#xA;@router.post(&amp;quot;/post2&amp;quot;)&#xA;async def post2(id: int = 1):&#xA;    session = Session()&#xA;    user = session.query(Models).filter(&#xA;        Models.id == id).first()&#xA;    for var in user.details:&#xA;        var.append({&amp;quot;b&amp;quot;: &amp;quot;200&amp;quot;})&#xA;    session.commit()&#xA;    return user&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;
        </summary>
    </entry>
    <entry>
        <id>https://stackoverflow.com/q/70236952</id>
        <re:rank scheme="https://stackoverflow.com">0</re:rank>
        <title type="text">Authentication dependency injection with password users and Google users</title>
        <category scheme="https://stackoverflow.com/tags" term="python" />
        <category scheme="https://stackoverflow.com/tags" term="authentication" />
        <category scheme="https://stackoverflow.com/tags" term="fastapi" />
        <author>
            <name>KOB</name>
            <uri>https://stackoverflow.com/users/4564080</uri>
        </author>
        <link rel="alternate" href="https://stackoverflow.com/questions/70236952/authentication-dependency-injection-with-password-users-and-google-users" />
        <published>2021-12-05T17:45:30Z</published>
        <updated>2021-12-05T17:45:30Z</updated>
        <summary type="html">
            &lt;p&gt;I am creating an app that allows users to either login with a username and password, or through Google authentication. I have signup and login working for both flows.  This is done by creating two separate login (and signup) endpoints for password and Google users.&lt;/p&gt;&#xA;&lt;p&gt;I am now working on using dependency injection to allow users to request various endpoints which will decode their JWT and return the data if they are authenticated, as shown here: &lt;a href=&quot;https://fastapi.tiangolo.com/tutorial/security/get-current-user/&quot; rel=&quot;nofollow noreferrer&quot;&gt;https://fastapi.tiangolo.com/tutorial/security/get-current-user/&lt;/a&gt;&lt;/p&gt;&#xA;&lt;p&gt;This works fine for users that have logged in with a username and password, since this dependency uses &lt;code&gt;OAuth2PasswordBearer&lt;/code&gt;.&lt;/p&gt;&#xA;&lt;p&gt;However, this of course does not work with my Google users since&lt;/p&gt;&#xA;&lt;ol&gt;&#xA;&lt;li&gt;They don&#x27;t have a password&lt;/li&gt;&#xA;&lt;li&gt;The &lt;code&gt;tokenUrl&lt;/code&gt; parameter for &lt;code&gt;OAuth2PasswordBearer&lt;/code&gt; is set to my password users&#x27; login endpoint.&lt;/li&gt;&#xA;&lt;/ol&gt;&#xA;&lt;p&gt;How can I achieve a &lt;code&gt;get_logged_in_user(token: str = Depends(oauth2_scheme))&lt;/code&gt; function that words both for users who have logged in with a password and those who have logged in through Google?&lt;/p&gt;&#xA;
        </summary>
    </entry>
</feed>